<?php
/** 
 * controller => create
 * action => success
 */
$this->headTitle(ucwords($this->type) . ' Created');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/create.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/invite.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/createsuccess.js');
?>

<div class='white-back dropshadow rounded-corners' id='create-success-container'>
    <header class='clear width-100 center margin-top jumbo-text heavy darkest'>
        <?php echo ucwords($this->type);?> Created!
    </header>
    <a href='/<?php echo $this->type . 's';?>/<?php echo $this->typeID;?>' class='light clear width-100 center'>view <?php echo $this->type;?> page</a>
    
    <?php
	echo $this->partial('partials/global/sectionHeaderBold.phtml',array('title'   => 'Invite players')); 
	?>
    
    <form action='/mail/invite-type' method='post' id='invite-form'>
    
    <?php echo $this->userName;?>
    <div class='clear' id='create-userName-results-container'>
    </div>
    
    <div class='clear larger-margin-top' id='userList'>
    </div>
    
	<p class='clear width-100 center larger-text light heavy margin-top'>or</p>
    
    <p class='left medium heavy larger-margin-top' id='invite-numEmails-container'><span class='inherit' id='invite-numEmails'>0</span> recipients</p>
    <div class='clear white-background dropshadow' id='profile-invite-emails-outer-container'>
    	<div class='clear width-100' id='profile-invite-parsedEmails'>
        </div>
        <?php echo $this->form->emailsTextArea;?>
    </div>
        
    
    <?php 
		echo $this->form->note;
		echo $this->form->emails;
	?>
    <p class='clear medium pointer margin-top' id='create-success-addNote'>+add personal note</p>
    <p class='clear medium pointer margin-top hidden' id='create-success-removeNote'>remove personal note</p>
    <input type='submit' class='clear right green-button largest-text heavy hidden' id='create-send-invites' value='Send Invites' />

    <input type='hidden' name='userIDs' id='userIDs' />
    <input type='hidden' name='<?php echo $this->type . 'ID';?>' value='<?php echo $this->typeID;?>' />
    
    

    
    </form>
    
    
</div>