<?php
/** 
 * controller => games
 * action => index
 */
$this->headTitle($this->game->type->typeName . ' ' . $this->game->sport);
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/game.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/profile.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/game.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/profile.js');
?>

<?php
if ($this->fail) {
	// No game found, show failure
	echo "<p class='larger-margin-top left jumbo-text heavy width-100 center darkest'>Game not found.</p>";
	echo "<p class='clear largest-text heavy darkest width-100 center'>This game was either deleted or has already happened.</p>";
	echo "<a href='/' class=' larger-margin-top clear larger-text medium width-100 center'>Back to home</a>";
	return;
}

echo $this->placeholder('absolute')->captureStart();
	echo $this->partial('partials/global/alertBack.phtml');
	echo $this->alert()->confirmAlert();
	
	if ($this->signupInvite) {
		echo $this->alert()->minimalSignup($this->user, $this->parkCityID, $this->game->park->location->location);
		
	}
	
	if (!$this->userInGame) {
		echo $this->usersideinfo($this->game->sport);
	}
	
	if ($this->stash) {
		echo $this->alert()->start('stash-available',"Stash available!");
		
		echo "<p class='clear medium width-100 center'><span class='darkest'>A stash is a public, free-to-use collection of sports equipment.</span>  <br>It contains useful items like cones, nets, and goals.</p>";
		
		echo "<a href='/parks/" . $this->game->park->parkID . "/stash' class='clear heavy largest-text button larger-margin-top game-stash-button' target='_blank'>view stash</a>";
		
		echo $this->alert()->end();
	}
	
	if ($this->addToGame) {
		// User not added to game from email
		echo $this->alert()->start('addToGame',"");
		
		echo "<p class='clear darkest width-100 center largest-text heavy'>" . $this->addToGame . "</p>";
				
		echo $this->alert()->end();
	}
	
	
	if ($this->captain) {
		// user is captain
		
		// Remove player alert
		echo $this->removeplayeralert($this->game->players->getAll());
		
		
		// Cancel game
		echo $this->alert()->start('manage-cancel',"Cancel game.");
			if ($this->game->recurring) {
				// recurring game, give option to cancel forever
				echo "<div class='width-100 left'><p class='larger-text darkest clear left' id='game-cancel-subscribe'>I want to cancel this game for </p>
						<select class='darkest left larger-text' id='cancel-game'><option>this week</option><option>ever</option></select>
					  </div>";
				echo "<div class='clear width-100' id='game-cancel-subscribe-container'></div>";
				echo "<p class='clear right button larger-margin-top' id='confirm-cancel'>Confirm</p>";
				echo "<p class='right smaller-text alert-cancel-button medium pointer'>Cancel</p>";
			} 
		
		echo $this->alert()->end();

	}
	
	if ($this->game->canceled) {
		// Game has been canceled
		echo $this->alert()->start('canceled');
			echo "<p class='largest-text darkest width-100 center heavy'>This game has been canceled.</p>";
			
			if ($this->game->cancelReason) {
				// Reason was given
				echo "<p class='light clear margin-top width-100 center'>Reason given...</p>";
				echo "<p class='darkest width-100 center clear'>" . $this->game->cancelReason . "</p>";
			}
			
			$leaveButton = '';
			$class = '';
			if ($this->userInGame) {
				$leaveButton = "<p class='right larger-margin-top larger-text heavy red-button' id='game-canceled-leave'>Leave Game</p>";
				$class = 'game-canceled-first';
			}
			
			echo $leaveButton; 
			echo "<a href='/' class='right larger-text larger-margin-top heavy button " . $class . "' id='game-canceled-back'>Back to home</a>";
			
			
		echo $this->alert()->end();
	}
	
	if ($this->topAlertProfilePicture) {
		echo $this->alert()->start('upload');
			echo "<p class='darkest width-100 center heavy'>You must upload a profile picture to receive any ratings.</p>";

			echo "<a href='/users/" . $this->user->userID . "/upload' class='clear right larger-text larger-margin-top heavy green-button white' id='game-canceled-back'>Upload Now</a>";
		echo $this->alert()->end();
		
		$content = "<a href='/users/" . $this->user->userID . "/upload' class='width-100 center white left heavy'>You need a profile picture to receive ratings.  <span class='white'>Click here to add one.</span></p>";
		echo $this->topalert('upload', $content);
	}
	
	if ($this->invitesSent ||
		$this->messageSent) {
		// Invites sent from previous page, show alert
		echo $this->alert()->start('success');
		echo "<p class='largest-text darkest width-100 center heavy'>" . ($this->invitesSent ? 'Invites' : 'Message') . " sent.</p>";

		echo $this->alert()->end();
	}
	
	
	if ($this->userInGame ||
		$this->captain ||
		$this->subscribed) {
			
		$this->headScript()->prependFile($this->baseUrl() . '/js/createsuccess.js');
		//$this->headLink()->prependStylesheet($this->baseUrl() . '/css/create.css');
		
		echo $this->alert()->inviteAlert($this->pendingInvites);
		
		echo $this->alert()->messageAlert();
		
		if ($this->game->isRecurring()) {
			echo $this->alert()->start('emails', 'Manage what emails you receive.');
			
			echo "<p class='heavy white dark-back clear section-header'>Weekly Reminder</p>
					<div class='clear margin-top larger-indent'>
						<p class='darkest clear' tooltip='Email reminders are sent the day before the game.'>Would you like to receive weekly reminders for this game?</p>";
			
			$yes = $no = false;
			if ($this->subscribed) {
				$yes = true;
			} else {
				$no = true;
			}
			
			$options = array('yes' => array('selected' => $yes),
							 'no' => array('selected' => $no));	
			echo "<div class='clear margin-top reminders-alert-yesno-container' id='reminders-alert-yesno-container'>";
			echo	$this->signupsportform()->selectableText($options, true);
			echo "</div>";
			
			if ($this->captain) {
				echo "<div class='clear larger-margin-top width-100'>
						<p class='clear margin-top light width-100 smaller-text'>Email reminders are sent to members <span class='medium'>the day before.</span></p>
						<p class='clear darkest  width-100'>What time would you like these reminders sent to your players?</p>
					  </div>";
				
				echo "<div class='clear width-100 larger-margin-top'>";
				echo $this->reminderHourDropdown;
				echo $this->reminderAmpmDropdown;
				echo "</div>";
			}
			echo "</div>";
			
			echo "<p class='heavy white dark-back clear section-header largest-margin-top'>Game On</p>";
			echo "<div class='clear margin-top larger-indent'>";


			$yes = $no = false;
			if ($this->game->gameOn) {
				$yes = true;
			} else {
				$no = true;
			}
			
			$options = array('yes' => array('selected' => $yes),
							 'no' => array('selected' => $no));	

			if ($this->captain) {
				echo "<p class='clear darkest width-100' tooltip='The system will check whether the minimum player limit has been reached and alert players accordingly.'>Do you want to send game on/off emails to members an hour before game time?</p>";
				
				echo "<div class='clear margin-top width-100 reminders-alert-yesno-container' id='reminders-alert-gameon-admin-yesno-container'>";
				echo	$this->signupsportform()->selectableText($options, true);
				echo "</div>";

			}
			
			
			
			if ($this->captain) {
				$members = $ins = false;
				if ($this->game->gameOn == '1') {
					$members = true;
				} else {
					$ins = true;
				}
				
				$class = '';
				if (!$members && !$ins) {
					// Game on is set to "no"
					$class = 'hidden';
				}
				
				echo "<div class='clear width-100 " . $class . "' id='reminders-alert-gameon-container'>";
				
				echo "<p class='clear darkest larger-margin-top'>Who should receive these game on emails?</p>";
				
				
				$options = array('ins & maybes' => array('selected' => $ins,
								 						 'tooltip' => 'The game on email will only be sent to those players who have responded "in" or "maybe"'),
								 'all members' => array('selected' => $members),
								 );	
								 
				echo "<div class='clear margin-top width-100 reminders-alert-yesno-container' id='reminders-alert-gameon-admin-who-container'>";
				echo	$this->signupsportform()->selectableText($options, true);
				echo "</div>";
				
				echo "</div>";

			}
			echo "<p class='darkest clear larger-margin-top' tooltip='The system alerts members whether there are enough players for their game an hour before game time.'>Would you like to receive" . ($this->captain ? ' these' : '') . " game on emails?</p>";
				
			$yes = $no = false;
			if ($this->emailGameOn) {
				$yes = true;
			} else {
				$no = true;
			}
			
			$options = array('yes' => array('selected' => $yes),
							 'no' => array('selected' => $no));		
				
			echo "<div class='clear margin-top reminders-alert-yesno-container' id='reminders-alert-gameon-yesno-container'>";
			echo	$this->signupsportform()->selectableText($options, true);
			echo "</div>";
			
			echo "</div>";
			
			
			echo $this->alert()->end();
		}
		
	}
		

	
echo $this->placeholder('absolute')->captureEnd();

// Narrow left column
$this->placeholder('narrowColumn')->captureStart();

//if ($this->userInGame) {
	// User is attending, show quick stats
	if ($this->gameOn) {	
		$gameFull = $maybe = '';
		if ($this->gameFull) {
			$gameFull = ' (FULL)';
		}
		if ($this->maybeConfirmedPlayers > 0) {
			$maybe = "<p class='white smaller-text clear'>+" . $this->maybeConfirmedPlayers . " maybe</p>";
		}
		
		echo "<div class='green-back white heavy narrow-overlay-container dropshadow'><p class='left inherit'>" . $this->confirmedPlayers . " " . ($this->confirmedPlayers == 1 ? 'player' : 'players') . " " . $gameFull .   "</p>" . $maybe . "</div>";
	} else {
		echo "<div class='dark-red-back white heavy narrow-overlay-container dropshadow' tooltip='" . ($this->game->minPlayers - $this->totalPlayers) . " more players are needed in order for this game to happen.'>"
			 . $this->confirmedPlayers . " " . ($this->confirmedPlayers == 1 ? 'player' : 'players') . " <br>
			 <span class='white'>" . $this->playersNeeded  . " needed</span>"
			 
			 . ($this->game->canceled ? "<br>CANCELED" : '') .
			 "</div>";
	}
//}

echo "<img src='" . $this->game->getProfilePic('large', 'parks') . "' class='rounded-corners narrow-column-picture dropshadow'/>";

if ($this->game->isRecurring()) {
	// Recurring game, show historical data
	echo "<a class='narrow-column-header clear darkest' href='/games/" . $this->game->gameID . "/stats'>Game Stats</a>";
}


$ratings = array('skill', 'sportsmanship', 'attendance');

echo $this->narrowcolumnsection()->start(array('title' => 'Avg Ratings'));

if ($this->game->players->hasValue('users')) {
	// Players exist, show average ratings
	echo "<div class='profile-narrow-rating-container clear'>";
	foreach ($ratings as $rating) {
		echo $this->partial('partials/global/ratingBar.phtml', array('rating' => $this->game->getAverage($rating),
																	 'ratingLabel' => $rating));
	}
	echo "</div>";
} else {
	// No players
	echo "<p class='width-100 left center light'>No players</p>";
}

echo $this->narrowcolumnsection()->end();

if (!$this->game->isRecurring()) {
	echo "<div class='width-100 left narrow-column-calendar-container'>";
	echo 	$this->calendar()->createCalendar(array($this->game), true, true, false, false, false, false, $this->game->gameID);
	echo "</div>";
}



$this->placeholder('narrowColumn')->captureEnd();

if ($this->game->hasCaptain()) {
	$captains = array_keys($this->game->captains);
	$captains = implode(',',$captains);
} else {
	$captains = '';
}
// Store universal game details in hidden container
echo "<span id='game-details' 
			gameID='" . $this->game->gameID . "' 
			idType='gameID' 
			actingUserID='" . $this->user->userID . "' 
			captains='" . $captains. "'
			city='" . $this->game->city . "'
			rosterLimit='" . $this->game->rosterLimit . "'
			sport='" . $this->game->sport . "'
			public='" . ($this->isPublic ? 'public' : 'private') . "'
			recurring = '" . ($this->game->isRecurring() ? 'true' : '') . "' 
			picture='" /*. (!$this->user->hasProfilePic() ? 'true' : '')*/ . "'>
	 </span>";
	 

?>

<?php
if ($this->topAlert && $this->userInGame) {
	// Game is recurring 
	/*
	echo $this->placeholder('topalert')->captureStart();
		$content = "<p class='white heavy width-100 center'>This game happens every week. <span class='white'> Click here to subscribe for weekly email reminders.</span></p>";
		echo $this->topalert('subscribe', $content);
	echo $this->placeholder('topalert')->captureEnd();
	
	$buttonID = 'subscribe-button';
	$buttonText = '+Subscribe';
	echo "<div class='dark-alert-box white heavy'>
				<span class='left inherit width-100 center'>This game happens every week.</span>
				<span class='clear inherit button  white pointer' id='" . $buttonID . "'>" . $buttonText . "</span>
		  </div>";
		  */
} elseif ($this->pastGame) {
	// This game already happened
	echo "<div class='red-alert-box white heavy'>This game already happened!</div>";
} elseif ($this->currentGame) {
	// This game already happened
	echo "<div class='green-alert-box white heavy'>This game is currently happening!</div>";
}
?>

<?php
if ($this->userInGame || 
	$this->subscribed ||
	$this->captain) {
	$options = array();
	$basicOptions = array(array('text' => 'invite',
								'img'  => 'invite',
								'tooltip' => 'Invite other players'),
						  );
	
	$playingOptions = array(array('text' => 'leave',
						  		'img'  => 'leave',
								'tooltip' => 'Leave this game')
							);
								
	$recurringOptions = array(array('text' => 'stats',
									'img'  => 'stats',
									'href' => '/games/' . $this->game->gameID . '/stats',
									'tooltip' => 'View historical stats for this game'),
							  array('text' => 'emails',
									'img'  => 'reminder',
									'tooltip' => 'Manage any emails for this game')
							  );
									
	$captainOptions = array(array('text' => 'edit game',
								  'img'  => 'edit',
								  'href' => '/games/' . $this->game->gameID . '/edit',
								  'tooltip' => "Edit this game's details"),
							array('text' => 'message',
								  'img'  => 'message',
								  'tooltip' => "Send an email message to the players"),
							array('text' => 'cancel',
								  'img'  => 'cancel',
								  'tooltip' => 'Cancel this game'));
	
	
	if ($this->captain) {
		// Is captain
		foreach ($captainOptions as $option) {
			$options[] = $option;
		}
	
	}
	
	if ($this->captain &&
		$this->game->isRecurring()) {
			$options[] = array('text' => 'members',
								  'img'  => 'subscribers',
								  'href' => '/games/' . $this->game->gameID . '/members',
								  'tooltip' => "View list of members");
		}
	
	if ($this->game->isRecurring()) {
		foreach ($recurringOptions as $option) {
			$options[] = $option;
		}
	}
	
	
	foreach ($basicOptions as $option) {
		$options[] = $option;
	}
	
	if ($this->userInGame) {
		foreach ($playingOptions as $option) {
			$options[] = $option;
		}
	}
	
	$args = array('options' => $options);
	
	if ($this->confirmed ||
		$this->captain) {
			// Is captain or confirmed, let add guest
			$args['guests'] = $this->userPlus;
			$args['game'] = $this->game;
		} 
	
	echo $this->partial('partials/profile/options.phtml', $args);
}
?>

<header class='clear profile-name-container'>
	<p class='profile-name heavy darkest clear'>
    	<?php echo $this->gameTitle;?>
	</p>
    <div class='profile-city-container clear'>
        <p class='darkest clear largest-text' tooltip='<?php echo $this->game->gameDate->format('M j');?>'>
            <?php echo $this->game->getDay() . ' at ' . $this->game->getHour();?>
        </p>  
        <a href='/parks/<?php echo $this->game->park->parkID;?>' class='clear darkest larger-text game-location'>
			<?php echo $this->game->park->parkName;?>
        </a>
        <a href='http://www.google.com/maps?f=d&q=<?php echo $this->parkLocation->latitude . ',' . $this->parkLocation->longitude;?>' class='left light game-distance smaller-text' target='_blank' tooltip='Get directions'>
			<?php echo ($this->user->location->latitude ? $this->game->park->getDistanceFromUser($this->user->location->latitude, $this->user->location->longitude) . " miles from you" : '');?> 
        </a>
        <?php 
		if ($this->game->hasValue('backupParkName')) {
		?>
			<a href='/parks/<?php echo $this->game->backupParkID;?>' class='clear light game-location' tooltip='If <?php echo $this->game->park->parkName;?> is unavailable, go to this nearby park instead.'>
				Backup park: <?php echo $this->game->backupParkName;?>
			</a> 
        <?php }
		
		if ($this->game->park->specialNotes) {
			echo "<div class='clear indent'>";
			echo	"<p class='clear red'>" . $this->game->park->specialNotes . "</p>";
			echo "</div>";
		}
		?>
        
    </div>
</header>


<?php

if (!$this->gameFull ||
	$this->userInGame) {
	echo $this->partial('partials/global/confirmed.phtml', array('game' => $this->game,
															   'userID' => $this->user->userID));
	/*														   
	if ($this->confirmed &&
		!$this->gameFull) {
		echo "<div class='right' id='game-guests-container'><p class='medium left smaller-text'>Guests?</p>";
		
		echo "<select class='smaller-text medium' id='game-plus'>";
        
                    for ($i = 0; $i < 3; $i++) {
						if ($i > ($this->game->rosterLimit - $this->confirmedPlayers)) {
							continue;
						}
                        $selected = '';
                        if ($this->userPlus == $i) {
                            $selected = 'selected';
                        }
                        echo "<option " . $selected . ">" . $i . "</option>";
                    }
               
        echo "</select></div>";
	}
	*/
} else {
	echo "<p class='right medium larger-margin-top'>This game is full.</p>";
}
            
if ($this->userInGame) {
?>
<!--
<div id='profile-buttons-container-holder' class='right'></div>
				

<div id='profile-buttons-container' holder='profile-buttons-container-holder' class='absolute'>
	<div class='profile-buttons-inner-container left'>
        <div class='profile-animate-buttons light-back pointer' tooltip='Show options'>
        	<img src='/images/global/arrows/left/medium.png' class='left' />
        </div>
        <div class='profile-buttons-innermost-container right'>
        <p class='dark smaller-text right current-position' >
        <?php 
            if ($this->userInGame) {
                ?>
            You are attending with 
              <select id='game-plus'>
                <?php
                    for ($i = 0; $i < 3; $i++) {
						if ($i > ($this->game->rosterLimit - count($this->game->players->getAll()))) {
							continue;
						}
                        $selected = '';
                        if ($this->userPlus == $i) {
                            $selected = 'selected';
                        }
                        echo "<option " . $selected . ">" . $i . "</option>";
                    }
                ?>
              </select>
            others.
            <?php }?>
        </p>
        
                <p class='red-button leave-button margin-top right clear-right-only' id='leave-button' style='margin-right:0'>
                    Leave
                </p>
            <?php 	
			if ($this->subscribed) {
				echo "<p class='medium margin-top right pointer' id='unsubscribe-button'>Unsubscribe</p>";
				}
			?>
                <div class='larger-margin-top clear-right-only right'>
                    <?php echo $this->inviteButton;?>
                </div>
        <?php 
            
            if ($this->captain) {
                // User is captain
                echo "<div class='larger-margin-top right profile-buttons-second-row'>" . $this->manageButton . "</div>";
            }
        ?>
        </div>
    </div>
</div>
-->

<?php
	} elseif (!$this->userInGame) {
		/*
		echo "<div class='right'>";
                $lower = '';
                $class = '';
                $text = 'Join';
                $id    = 'join-button';
                $tooltip = '';
				if ($this->gameFull) {
					// Game is full, do not let join
					echo "<p class='right green heavy'>This game is full</p>";
				} else {
					if (!$this->isPublic) {
						// Not sportfast created team, allow any user to join without request
						$text = 'Request to Join';
						$id   = 'request-join-button';
						$tooltip = "tooltip='This is a private game.'";
					} elseif ($this->userHasSport) {
					
						if ($this->game->minSkill > $this->user->getSport($this->game->sport)->overall) {
							// User is not good enough for this game
							$class = 'transparent default';
							$id = '';
							$lower = '<p class="light clear-right smaller-text margin-top">You must have a minimum skill of ' . $this->game->minSkill . ' to join.</p>';
						} elseif ($this->game->maxSkill < $this->user->getSport($this->game->sport)->overall) {
							 // User is too good 
							$class = 'transparent default';
							$id = '';
							$lower = '<p class="light clear-right smaller-text margin-top">You must have a maximum skill of ' . $this->game->maxSkill . ' to join.</p>';
						}
					} elseif (!$this->userHasSport) {
						// User does not have sport
						$text = 'Sport Needed';
						$class = 'transparent default';
						$id   = 'join-sport-needed';
						$tooltip = "tooltip='You do not have this sport included in your profile.  Add it under Account Settings.'";
					}
					
					/*
					if (!$this->user->hasProfilePic()) {
						// User does not have profile pic, do not allow to join
						$class = 'transparent default';
						$tooltip = "tooltip='You must upload a picture before you can join any games.'";
					}
					
					
					if ($this->subscribed) {
						$lower = "<p class='medium margin-top clear-right pointer' style='margin-right:.4em' id='unsubscribe-button'>Unsubscribe</p>";
					}
					?>
					<p class='green-button right larger-text join-button heavy <?php echo $class;?>' <?php echo $tooltip;?> id='<?php echo $id;?>'>
						<?php echo $text;?>
					</p>
                    <div class='right profile-in-out-container'>
                    	<?php 
							$in = $out = $maybe = '';
							$selected = 'member-schedule-button-selected';
							if ($this->game->userConfirmed($this->user->userID)) {
								$in = $selected;
							} elseif ($this->game->userNotConfirmed($this->user->userID)) {
								$out = $selected;
							} elseif ($this->game->userMaybeConfirmed($this->user->userID)) {
								$maybe = $selected;
							}
							?>

                        <p class='clear-right button schedule-out larger-text heavy <?php echo $out;?>'>out</p>
                        <p class='right button schedule-in larger-text heavy <?php echo $in;?>'>in</p>
                        <p class='clear-right button smaller-text schedule-maybe <?php echo $maybe;?>'>maybe</p>
                    </div>
					<?php echo $lower; ?>
                <?php } ?>
           </div>
        <?php*/ } ?>

<!--
    <div class='clear width-100 larger-margin-top'>
    	<div class='left game-rating-box green-back rounded-corners'>
        	<p class='largest-text white width-100 center heavy'>88</p>
        </div>
        <div class='left game-rating-box green-back rounded-corners'>
        	<p class='largest-text white width-100 center heavy'>88</p>
        </div>
        <div class='left game-rating-box green-back rounded-corners'>
        	<p class='largest-text white width-100 center heavy'>88</p>
        </div>
    </div>-->
<?php
/*
if ($this->showSubscribe) {
	echo "<div class='green-alert-box ' id='subscribe-container'>
			<p class='white heavy'>This game happens every week.  <br><span class='white action pointer' id='subscribe'>Click here for weekly email reminders.</span></p>
			<p class='pointer white' id='subscribe-x'>x</p>
		  </div>";
}
*/

// Create header for players section
$playersHeader  = "<div class='right profile-section-bold-subheader'>";
$playersHeader .= 		"<p class='right heavy darkest'>" . $this->confirmedPlayers . " players <span class='medium smaller-text'>" . ($this->maybeConfirmedPlayers > 0 ? '+' . $this->maybeConfirmedPlayers . ' maybe' : '') . "</span></p>";
$playersHeader .= "</div>";

$playersHeader .= "<div class='left profile-section-bold-subheader team-player-going-description-container'>";
//$playersHeader .= 		"<img class='left' src='/images/team/confirm/small.png' />";
$playersHeader .=		"<div class='left green-back profile-confirm'></div>";
$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>In</p>";
//$playersHeader .= 		"<img class='left' src='/images/team/deny/small.png' />";
$playersHeader .=		"<div class='left dark-red-back profile-confirm'></div>";
$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Out</p>";
$playersHeader .=		"<div class='left light-background profile-confirm'></div>";
$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Maybe</p>";
$playersHeader .= "</div>";
/*
if ($this->nextGame) {
	$playersHeader .= "<div class='left profile-section-bold-subheader team-player-going-description-container'>";
	$playersHeader .= 		"<img class='left' src='/images/team/confirm/small.png' />";
	$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Going to next game</p>";
	$playersHeader .= 		"<img class='left' src='/images/team/deny/small.png' />";
	$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Not going to next game</p>";
	$playersHeader .= "</div>";
}*/
echo $this->partial('partials/global/sectionHeaderBold.phtml',array('title'   => 'players',
																	'content' => $playersHeader)); 

echo "<div id='team-players-container' class='clear width-100'>";

// Players exist
echo $this->playerssection($this->game->players->users);

echo "</div>";

if ($this->similarGames) {
	$similarGames = $this->similarGames->getAll();
	$similarGame = $similarGames[0];
	echo "<div class='clear game-similar-container width-100'>
			<p class='clear medium'>Members of this game also play...</p>
			<a href='/games/" . $similarGame->gameID . "' class='clear find-result-container animate-darker' gameID='" . $similarGame->gameID . "'>
				<img src='" . $similarGame->getProfilePic('medium') . "' class='left img-medium-small'/>
			
				<div class='left find-result-left-container'>
					<p class='clear larger-text darkest heavy'>" . $similarGame->getGameTitle() . "</p>
					<p class='clear darkest'>" . $similarGame->getGameDays() . "</p>
					<p class='clear medium'>" . $similarGame->park->parkName . "</p>
				</div>
				
				<div class='right find-result-right-container'>
					<p class='clear-right smaller-text medium'>You are not a member of this game</p>
					<p class='clear-right button' id='game-become-member'>Become member</p>

				</div>
			</a>
		</div>";
}

// Recent Activity section
echo $this->partial('partials/global/sectionHeaderPlain.phtml',array('title' => 'Recent Activity'));

if ($this->userInGame) {
	// User is on team, allow to post
?>
<div id='team-post-container' class='clear width-100'>
	<?php echo $this->user->getBoxProfilePic('small');?>
    <?php echo $this->postForm;?>
</div>

<?php
	}
echo $this->profilenewsfeed()->create($this->newsfeed);
?>

