<?php
/** 
 * controller => games
 * action => index
 */
$this->headTitle($this->game->type->typeName . ' ' . $this->game->sport);
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/game.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/profile.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/game.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/profile.js');
?>

<?php
if ($this->fail) {
	// No game found, show failure
	echo "<p class='larger-margin-top left jumbo-text heavy width-100 center darkest'>Game not found.</p>";
	echo "<p class='clear largest-text heavy darkest width-100 center'>This game was either deleted or has already happened.</p>";
	echo "<a href='/' class=' larger-margin-top clear larger-text medium width-100 center'>Back to home</a>";
	return;
}

echo $this->placeholder('absolute')->captureStart();
	echo $this->partial('partials/global/alertBack.phtml');
	echo $this->alert()->confirmAlert();
	
	
	if (!$this->userInGame) {
		echo $this->usersideinfo($this->game->sport);
	}
	
	
	if ($this->captain) {
		// user is captain
		
		// Remove player alert
		echo $this->removeplayeralert($this->game->players->getAll());
		
		
		// Edit game info alert
		echo $this->alert()->start('manage-game-info',"Click on anything to edit.");
		
		echo $this->alert()->end();
		
		// Cancel game
		echo $this->alert()->start('manage-cancel',"Cancel game.");
			if ($this->game->recurring) {
				// recurring game, give option to cancel forever
				echo "<div class='width-100 left'><p class='larger-text darkest clear left' id='game-cancel-subscribe'>I want to cancel this game for </p>
						<select class='darkest left larger-text' id='cancel-game'><option>this week</option><option>ever</option></select>
					  </div>";
				echo "<div class='clear width-100' id='game-cancel-subscribe-container'></div>";
				echo "<p class='clear right button larger-margin-top' id='confirm-cancel'>Confirm</p>";
				echo "<p class='right smaller-text alert-cancel-button medium pointer'>Cancel</p>";
			} 
		
		echo $this->alert()->end();

	}
	
	if ($this->game->canceled) {
		// Game has been canceled
		echo $this->alert()->start('canceled');
			echo "<p class='largest-text darkest width-100 center heavy'>This game has been canceled.</p>";
			
			if ($this->game->cancelReason) {
				// Reason was given
				echo "<p class='light clear margin-top width-100 center'>Reason given...</p>";
				echo "<p class='darkest width-100 center clear'>" . $this->game->cancelReason . "</p>";
			}
			
			echo "<a href='/' class='clear larger-text larger-margin-top heavy green-button white' id='game-canceled-back'>Back to home</a>";
			if ($this->userInGame) {
				echo "<p class='right larger-margin-top larger-text heavy red-button' id='game-canceled-leave'>Leave Game</p>";
			}
		echo $this->alert()->end();
	}
	
	if (!$this->user->hasProfilePic()) {
		echo $this->alert()->start('upload');
			echo "<p class='darkest width-100 center heavy'>You must upload a profile picture before joining a game.</p>";

			echo "<a href='/users/" . $this->user->userID . "/upload' class='clear larger-text larger-margin-top heavy green-button white' id='game-canceled-back'>Upload Now</a>";
		echo $this->alert()->end();
		
		$content = "<a href='/users/" . $this->user->userID . "/upload' class='width-100 center white left heavy'>You need a profile picture to play.  <span class='white'>Click here to add one.</span></p>";
		echo $this->topAlert('upload', $content);
	}
		

	
echo $this->placeholder('absolute')->captureEnd();

// Narrow left column
$this->placeholder('narrowColumn')->captureStart();

if ($this->userInGame) {
	// User is attending, show quick stats
	if ($this->gameOn) {	
		echo "<div class='green-back white heavy narrow-overlay-container dropshadow'>" . $this->totalPlayers . " " . ($this->totalPlayers == 1 ? 'player' : 'players') . "</div>";
	} else {
		echo "<div class='dark-red-back white heavy narrow-overlay-container dropshadow' tooltip='" . ($this->game->minPlayers - $this->totalPlayers) . " more players are needed in order for the game to happen.'>"
			 . $this->playersNeeded  . " needed
			 </div>";
	}
}

echo "<img src='" . $this->game->getProfilePic('large', 'parks') . "' class='rounded-corners narrow-column-picture dropshadow'/>";

$ratings = array('skill', 'sportsmanship', 'attendance');

echo $this->narrowcolumnsection()->start(array('title' => 'Avg Ratings'));

if ($this->game->players->hasValue('users')) {
	// Players exist, show average ratings
	echo "<div class='profile-narrow-rating-container clear'>";
	foreach ($ratings as $rating) {
		echo $this->partial('partials/global/ratingBar.phtml', array('rating' => $this->game->getAverage($rating),
																	 'ratingLabel' => $rating));
	}
	echo "</div>";
} else {
	// No players
	echo "<p class='width-100 left center light'>No players</p>";
}

echo $this->narrowcolumnsection()->end();


echo "<div class='width-100 left narrow-column-calendar-container'>";
echo 	$this->calendar()->createCalendar(array($this->game), true);
echo "</div>";



$this->placeholder('narrowColumn')->captureEnd();

if ($this->game->hasCaptain()) {
	$captains = array_keys($this->game->captains);
	$captains = implode(',',$captains);
} else {
	$captains = '';
}
// Store universal game details in hidden container
echo "<span id='game-details' 
			gameID='" . $this->game->gameID . "' 
			idType='gameID' 
			actingUserID='" . $this->user->userID . "' 
			captains='" . $captains. "'
			city='" . $this->game->city . "'
			rosterLimit='" . $this->game->rosterLimit . "'
			sport='" . $this->game->sport . "'
			public='" . ($this->isPublic ? 'public' : 'private') . "'
			picture='" . (!$this->user->hasProfilePic() ? 'true' : '') . "'
	 </span>";
?>

<?php
if ($this->topAlert && $this->userInGame) {
	// Game is recurring 
	echo $this->placeholder('topAlert')->captureStart();
		$content = "<p class='white heavy width-100 center'>This game happens every week. <span class='white'> Click here to subscribe.</span></p>";
		echo $this->topalert('subscribe', $content);
	echo $this->placeholder('topAlert')->captureEnd();
	/*
	$buttonID = 'subscribe-button';
	$buttonText = '+Subscribe';
	echo "<div class='dark-alert-box white heavy'>
				<span class='left inherit width-100 center'>This game happens every week.</span>
				<span class='clear inherit button  white pointer' id='" . $buttonID . "'>" . $buttonText . "</span>
		  </div>";
		  */
} elseif ($this->pastGame) {
	// This game already happened
	echo "<div class='red-alert-box white heavy'>This game already happened!</div>";
} elseif ($this->todayGame) {
	// This game is happening today
	echo "<div class='green-alert-box white heavy'>This game is happening today at " . $this->game->gameDate->format('g:ia') . "!</div>";
}
?>


<header class='clear profile-name-container'>
	<p class='profile-name heavy darkest clear'>
    	<?php echo $this->gameTitle;?>
	</p>
    <div class='profile-city-container clear'>
        <p class='darkest clear largest-text'>
            <?php echo $this->game->getDay() . ' at ' . $this->game->getHour();?>
        </p>  
        <a href='/parks/<?php echo $this->game->park->parkID;?>' class='clear darkest larger-text game-location'>
			<?php echo $this->game->park->parkName;?>
        </a>
        <a href='http://www.google.com/maps?q=<?php echo $this->parkLocation->latitude . ',' . $this->parkLocation->longitude;?>' class='left light game-distance smaller-text'>
			<?php echo $this->game->park->getDistanceFromUser($this->user->location->latitude, $this->user->location->longitude);?> miles from you
        </a>
        <?php 
		if ($this->game->hasValue('backupParkName')) {
		?>
			<a href='/parks/<?php echo $this->game->backupParkID;?>' class='clear light game-location' tooltip='If <?php echo $this->game->park->parkName;?> is unavailable, go to this nearby park instead.'>
				Backup park: <?php echo $this->game->backupParkName;?>
			</a> 
        <?php }?>
    </div>
</header>

<?php
            
if ($this->userInGame) {
?>
<div id='profile-buttons-container-holder' class='right'></div>
<div id='profile-buttons-container' holder='profile-buttons-container-holder' class='absolute'>
	<div class='profile-buttons-inner-container left'>
        <div class='profile-animate-buttons light-back pointer' tooltip='Show options'>
        	<img src='/images/global/arrows/left/medium.png' class='left' />
        </div>
        <div class='profile-buttons-innermost-container right'>
        <p class='dark smaller-text right current-position' >
        <?php 
            if ($this->userInGame) {
                ?>
            You are attending with 
              <select id='game-plus'>
                <?php
                    for ($i = 0; $i < 4; $i++) {
                        $selected = '';
                        if ($this->userPlus == $i) {
                            $selected = 'selected';
                        }
                        echo "<option " . $selected . ">" . $i . "</option>";
                    }
                ?>
              </select>
            others.
            <?php }?>
        </p>
        
                <p class='red-button leave-button margin-top right clear-right-only' id='leave-button' style='margin-right:0'>
                    Leave
                </p>
            <?php 	
			if ($this->subscribed) {
				echo "<p class='light margin-top right pointer' id='unsubscribe-button'>Unsubscribe</p>";
				}
			?>
                <div class='larger-margin-top clear-right-only right'>
                    <?php echo $this->inviteButton;?>
                </div>
        <?php 
            
            if ($this->captain) {
                // User is captain
                echo "<div class='larger-margin-top right profile-buttons-second-row'>" . $this->manageButton . "</div>";
            }
        ?>
        </div>
    </div>
</div>
<?php
	} elseif (!$this->userInGame) {
		echo "<div class='right'>";
                $lower = '';
                $class = '';
                $text = 'Join';
                $id    = 'join-button';
                $tooltip = '';
                if (!$this->isPublic) {
                    // Not sportup created team, allow any user to join without request
                    $text = 'Request to Join';
                    $id   = 'request-join-button';
                    $tooltip = "tooltip='This is a private game.'";
                }
				
                if ($this->game->minSkill > $this->user->getSport($this->game->sport)->overall) {
                    // User is not good enough for this game
                    $class = 'transparent default';
                    $id = '';
                    $lower = '<p class="light clear-right smaller-text margin-top">You must have a minimum skill of ' . $this->game->minSkill . ' to join.</p>';
                } elseif ($this->game->maxSkill < $this->user->getSport($this->game->sport)->overall) {
					 // User is too good 
                    $class = 'transparent default';
                    $id = '';
                    $lower = '<p class="light clear-right smaller-text margin-top">You must have a maximum skill of ' . $this->game->maxSkill . ' to join.</p>';
				}
					
				if (!$this->user->hasProfilePic()) {
					// User does not have profile pic, do not allow to join
					$class = 'transparent default';
					$tooltip = "tooltip='You must upload a picture before you can join any games.'";
				}
                ?>
                <p class='green-button right larger-text join-button heavy <?php echo $class;?>' <?php echo $tooltip;?> id='<?php echo $id;?>'>
                    <?php echo $text;?>
                </p>
                <?php echo $lower; ?>
           </div>
        <?php } ?>
<!--
    <div class='clear width-100 larger-margin-top'>
    	<div class='left game-rating-box green-back rounded-corners'>
        	<p class='largest-text white width-100 center heavy'>88</p>
        </div>
        <div class='left game-rating-box green-back rounded-corners'>
        	<p class='largest-text white width-100 center heavy'>88</p>
        </div>
        <div class='left game-rating-box green-back rounded-corners'>
        	<p class='largest-text white width-100 center heavy'>88</p>
        </div>
    </div>-->
<?php
// Create header for players section
$playersHeader  = "<div class='right profile-section-bold-subheader'>";
$playersHeader .= 		"<p class='right heavy darkest'>" . $this->totalPlayers . " out of " . $this->rosterLimit . "</p>";
$playersHeader .= "</div>";
/*
if ($this->nextGame) {
	$playersHeader .= "<div class='left profile-section-bold-subheader team-player-going-description-container'>";
	$playersHeader .= 		"<img class='left' src='/images/team/confirm/small.png' />";
	$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Going to next game</p>";
	$playersHeader .= 		"<img class='left' src='/images/team/deny/small.png' />";
	$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Not going to next game</p>";
	$playersHeader .= "</div>";
}*/
echo $this->partial('partials/global/sectionHeaderBold.phtml',array('title'   => 'players',
																	'content' => $playersHeader)); 

echo "<div id='team-players-container' class='clear width-100'>";

// Players exist
echo $this->playerssection($this->game->players->users);

echo "</div>";

// Recent Activity section
echo $this->partial('partials/global/sectionHeaderPlain.phtml',array('title' => 'Recent Activity'));

if ($this->userInGame) {
	// User is on team, allow to post
?>
<div id='team-post-container' class='clear width-100'>
	<?php echo $this->user->getBoxProfilePic('small');?>
    <?php echo $this->postForm;?>
</div>

<?php
	}
echo $this->profilenewsfeed()->create($this->newsfeed);
?>

