<?php
/** 
 * controller => games
 * action => index
 */
$this->headTitle($this->game->type->typeName . ' ' . $this->game->sport);
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/game.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/profile.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/game.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/profile.js');
?>

<?php
echo $this->placeholder('absolute')->captureStart();
	echo $this->partial('partials/global/alertBack.phtml');
	echo $this->alert()->start('confirm-action','');
	echo 	"<p class='width-100 clear center'>&nbsp;Are you sure you want to <span id='confirm-action-text'></span>?</p>";
	echo	"<p class='button clear' id='confirm-action'>Yes</p>";
	echo	"<p class='button' id='deny-action'>No</p>";
	echo $this->alert()->end();	
echo $this->placeholder('absolute')->captureEnd();

// Narrow left column
$this->placeholder('narrowColumn')->captureStart();

if ($this->userInGame) {
	// User is attending, show quick stats
	if ($this->gameOn) {	
		echo "<div class='green-back white heavy narrow-overlay-container dropshadow'>" . $this->totalPlayers . " " . ($this->totalPlayers == 1 ? 'player' : 'players') . "</div>";
	} else {
		echo "<div class='dark-red-back white heavy narrow-overlay-container dropshadow' tooltip='" . ($this->game->minPlayers - $this->totalPlayers) . " more players are needed in order for the game to happen.'>"
			 . $this->playersNeeded  . " needed
			 </div>";
	}
}

echo "<img src='" . $this->game->getProfilePic('large', 'parks') . "' class='rounded-corners narrow-column-picture dropshadow'/>";

$ratings = array('skill', 'sportsmanship', 'attendance');

echo $this->narrowcolumnsection()->start(array('title' => 'Avg Ratings'));

if ($this->game->players->hasValue('users')) {
	// Players exist, show average ratings
	echo "<div class='profile-narrow-rating-container clear'>";
	foreach ($ratings as $rating) {
		echo $this->partial('partials/global/ratingBar.phtml', array('rating' => $this->game->getAverage($rating),
																	 'ratingLabel' => $rating));
	}
	echo "</div>";
} else {
	// No players
	echo "<p class='width-100 left center light'>No players</p>";
}

echo $this->narrowcolumnsection()->end();


echo "<div class='width-100 left narrow-column-calendar-container'>";
echo 	$this->calendar()->createCalendar(array($this->game), true);
echo "</div>";



$this->placeholder('narrowColumn')->captureEnd();

if ($this->game->hasCaptain()) {
	$captains = array_keys($this->game->captains);
	$captains = implode(',',$captains);
} else {
	$captains = '';
}
// Store universal game details in hidden container
echo "<span id='game-details' 
			gameID='" . $this->game->gameID . "' 
			idType='gameID' 
			actingUserID='" . $this->user->userID . "' 
			captains='" . $captains. "'
			city='" . $this->game->city . "'
			rosterLimit='" . $this->game->rosterLimit . "'
			sport='" . $this->game->sport . "'
			public='" . ($this->isPublic ? 'public' : 'private') . "'
	 </span>";
?>

<?php
if (($this->game->recurring && $this->userInGame)) {
	// Game is recurring 
	$buttonID = 'game-subscribe';
	$buttonText = '+Subscribe';
	if ($this->game->isSubscriber($this->user->userID)) {
		$buttonID = 'game-unsubscribe';
		$buttonText = 'Unsubscribe';
	}
	echo "<div class='dark-alert-box white heavy'>
				<span class='left inherit width-100 center'>This game happens every week.</span>
				<span class='clear inherit button  white pointer' id='" . $buttonID . "'>" . $buttonText . "</span>
		  </div>";
} elseif ($this->pastGame) {
	// This game already happened
	echo "<div class='red-alert-box white heavy'>This game already happened!</div>";
} elseif ($this->todayGame) {
	// This game is happening today
	echo "<div class='green-alert-box white heavy'>This game is happening today at " . $this->game->gameDate->format('g:ia') . "!</div>";
}
?>

<p class='dark smaller-text right current-position' >
<?php 
	if ($this->userInGame) {
		?>
    You are attending with 
      <select id='game-plus'>
      	<?php
			for ($i = 0; $i < 4; $i++) {
				$selected = '';
				if ($this->userPlus == $i) {
					$selected = 'selected';
				}
				echo "<option " . $selected . ">" . $i . "</option>";
			}
        ?>
      </select>
    others.
    <?php }?>
</p>

<header class='clear profile-name-container'>
	<p class='profile-name heavy darkest clear'>
    	<?php echo $this->gameTitle;?>
	</p>
    <div class='profile-city-container clear'>
        <p class='darkest clear largest-text'>
            <?php echo $this->game->getDay() . ' at ' . $this->game->getHour();?>
        </p>  
        <a href='/parks/<?php echo $this->game->park->parkID;?>' class='clear darkest larger-text game-location'>
			<?php echo $this->game->park->parkName;?>
        </a>
        <a href='http://www.google.com/maps?q=<?php echo $this->parkLocation->latitude . ',' . $this->parkLocation->longitude;?>' class='left light game-distance smaller-text'>
        	&nbsp;&nbsp;
			<?php echo $this->game->park->getDistanceFromUser($this->user->location->latitude, $this->user->location->longitude);?> miles from you
        </a>
        <a href='/parks/<?php echo $this->game->backupParkID;?>' class='clear light game-location' tooltip='If <?php echo $this->game->park->parkName;?> is unavailable, go to this nearby park instead.'>
        	Backup park: <?php echo $this->game->backupParkName;?>
        </a> 
    </div>
</header>


<div id='profile-buttons-container' holder='profile-buttons-container-holder'>
    <?php
		
		if ($this->userInGame) {
			// You are in game
			?>
			<p class='red-button clear-right leave-button margin-top right' id='leave-button' style='margin-right:0'>
				Leave
			</p>
            <div class='clear-right larger-margin-top'>
            	<?php echo $this->inviteButton;?>
            </div>
    <?php } else {
			$lower = '';
			$class = '';
			$text = 'Join';
			$id    = 'join-button';
			$tooltip = '';
			if (!$this->isPublic) {
				// Not sportup created team, allow any user to join without request
				$text = 'Request to Join';
				$id   = 'request-join-button';
				$tooltip = "tooltip='This is a private game.'";
			}
			if ($this->game->minSkill > $this->user->getSport($this->game->sport)->skill) {
				// User is not good enough for this game
				$class = 'transparent default';
				$id = '';
				$lower = '<p class="light clear-right smaller-text margin-top">You must have a minimum skill of ' . $this->team->minSkill . ' to join.';
			}
			?>
    		<p class='green-button clear-right larger-text join-button heavy <?php echo $class;?>' <?php echo $tooltip;?> id='<?php echo $id;?>'>
            	<?php echo $text;?>
            </p>
            <?php echo $lower; ?>
    <?php } 
		
		if ($this->captain) {
			// User is captain
			echo "<div class='larger-margin-top right profile-buttons-second-row'>" . $this->manageButton . "</div>";
		}
	?>
</div>
<!--
    <div class='clear width-100 larger-margin-top'>
    	<div class='left game-rating-box green-back rounded-corners'>
        	<p class='largest-text white width-100 center heavy'>88</p>
        </div>
        <div class='left game-rating-box green-back rounded-corners'>
        	<p class='largest-text white width-100 center heavy'>88</p>
        </div>
        <div class='left game-rating-box green-back rounded-corners'>
        	<p class='largest-text white width-100 center heavy'>88</p>
        </div>
    </div>-->
<?php
// Create header for players section
$playersHeader  = "<div class='right profile-section-bold-subheader'>";
$playersHeader .= 		"<p class='right heavy darkest'>" . $this->totalPlayers . " out of " . $this->rosterLimit . "</p>";
$playersHeader .= "</div>";
/*
if ($this->nextGame) {
	$playersHeader .= "<div class='left profile-section-bold-subheader team-player-going-description-container'>";
	$playersHeader .= 		"<img class='left' src='/images/team/confirm/small.png' />";
	$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Going to next game</p>";
	$playersHeader .= 		"<img class='left' src='/images/team/deny/small.png' />";
	$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Not going to next game</p>";
	$playersHeader .= "</div>";
}*/
echo $this->partial('partials/global/sectionHeaderBold.phtml',array('title'   => 'players',
																	'content' => $playersHeader)); 

echo "<div id='team-players-container' class='clear width-100'>";

if ($this->game->players->hasValue('users')) {
	// Players exist
	echo $this->playerssection($this->game->players->users);
} else {
	echo "<p class='none-text larger-text light width-100 center'>There are no players.</p>";
}
echo "</div>";

// Recent Activity section
echo $this->partial('partials/global/sectionHeaderPlain.phtml',array('title' => 'Recent Activity'));

if ($this->userInGame) {
	// User is on team, allow to post
?>
<div id='team-post-container' class='clear width-100'>
	<img src='<?php echo $this->user->getProfilePic('small');?>' class='left' />
    <?php echo $this->postForm;?>
</div>

<?php
	}
echo $this->profilenewsfeed()->create($this->newsfeed);
?>

