<?php
/** 
 * controller => games
 * action => invite
 */
$this->headTitle(ucwords($this->type) . ' Invite');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/profile.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/invite.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/createsuccess.js');
?>

<div id='profile-invite-container'>
	<p class='largest-text darkest heavy clear'>Invite <span class='smaller-text darkest'>to game</span></p>
    <div class='white-back clear dropshadow'>
    <?php
	//echo $this->partial('partials/global/sectionHeaderBold.phtml',array('title'   => 'Invite players')); 
	?>
    
    
    <form action='/mail/invite-type' method='post' id='invite-form'>
    
  	<p class='left medium heavy larger-margin-top' id='invite-numEmails-container'><span class='inherit' id='invite-numEmails'>0</span> recipients</p>
    <div class='clear white-background dropshadow' id='profile-invite-emails-outer-container'>
    	<div class='clear width-100' id='profile-invite-parsedEmails'>
        </div>
        <?php echo $this->form->emailsTextArea;?>
    </div>
        
    
    <?php 
		echo $this->form->note;
		echo $this->form->emails;
	?>
    <p class='clear medium pointer margin-top' id='create-success-addNote'>+add personal note</p>
    <p class='clear medium pointer margin-top hidden' id='create-success-removeNote'>remove personal note</p>
    
    <a href='/<?php echo $this->type;?>s/<?php echo $this->typeID;?>' class='clear smaller-text medium profile-invite-back'><img src='/images/global/body/single_left_arrow.png' class='back-arrow'/>Back to game</a>

    <input type='submit' class='right green-button largest-text heavy larger-margin-top' id='profile-send-invites' value='Send Invites' />

    <input type='hidden' name='<?php echo $this->type . 'ID';?>' value='<?php echo $this->typeID;?>' />
    
    </form>
    </div>
</div>