<?php
/** 
 * controller => games
 * action => subscribers
 */
$this->headTitle('Game Members');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/profile.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/game.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/gamemembers.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/profile.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/createsuccess.js');


?>

<?php

$this->placeholder('narrowColumn')->captureStart();

echo "<img src='" . $this->game->park->getProfilePic('large') . "' class='clear narrow-column-picture' />";

echo "<div class='clear larger-margin-top larger-text width-100'>
		<p class='clear heavy darkest width-100 center'>" . $this->game->getGameTitle() . "</p>
		<p class='clear darkest width-100 center smaller-text'>" . $this->game->gameDate->format('l') . "s at " . $this->game->gameDate->format('g') . ($this->game->gameDate->format('i') != 0 ? ':' . $this->game->gameDate->format('i') : '') . $this->game->gameDate->format('a') . "</p>
	  	<p class='clear medium width-100 center smaller-text'>" . $this->game->park->parkName . "</p>
	  </div>";

$this->placeholder('narrowColumn')->captureEnd();

// Store universal game details in hidden container
echo "<span id='game-details' 
			gameID='" . $this->game->gameID . "' 
			idType='gameID' 
			actingUserID='" . $this->user->userID . "' 
			city='" . $this->game->city . "'
			rosterLimit='" . $this->game->rosterLimit . "'
			sport='" . $this->game->sport . "'
			public='" . ($this->isPublic ? 'public' : 'private') . "'
			recurring = '" . ($this->game->isRecurring() ? 'true' : '') . "' 
			picture='" /*. (!$this->user->hasProfilePic() ? 'true' : '')*/ . "'>
	 </span>";



echo $this->partial('partials/global/backTo.phtml', array('type' => 'game',
														  'id' => $this->game->gameID));


$content = "<p class='right heavy darkest profile-section-bold-subheader'>" . count($this->game->subscribers) . " total members</p>";

echo "<div class='clear width-100' id='game-subscribers-header-container'>";
echo $this->partial('partials/global/sectionHeaderBold.phtml', array('title' => 'members',
																	 'content' => $content));

echo "</div>";																 
?>

<?php
$members = $this->subscribers->getAll();

echo $this->pagination()->start($members, array('partial' => 'partials/games/members.phtml', 
												'attrib' =>  'user'));
/*
echo $this->pagination()->start($members, array('partial' => 'partials/games/members.phtml',
												'attrib' => 'user'));*/
												
?>

<?php
if ($this->captain) {
	
	echo "<div class='clear width-100 larger-margin-top'>";
	echo	"<p class='darkest heavy clear width-100 center larger-margin-top'>Add Member</p>";

	echo $this->form->text->setAttrib('id', 'inviteSearchAlert')
						  ->setLabel("Start typing a player's name...");

						  
	echo "<div class='clear width-100' id='invite-alert-results'></div>";
	echo "</div>";

?>
																 
<script>
var membersArray = [];
<?php
	foreach ($members as $member) {
		echo "membersArray.push('" . $member->userID . "');";
	}
?>
</script>

<?php } ?>

