<?php
/** 
 * controller => games
 * action => history
 */
$this->headTitle('Game Stats');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/history.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/history.js');
$this->headScript()->prependFile('https://www.google.com/jsapi');
?>

<?php
$this->placeholder('narrowColumn')->captureStart();

echo "<img src='" . $this->game->getProfilePic('large', 'parks') . "' class='rounded-corners narrow-column-picture dropshadow'/>";

echo "<div class='clear larger-margin-top larger-text width-100'>";
echo	"<p class='clear heavy width-100 center'>" . $this->game->getGameTitle() . "</p>";
echo	"<p class='clear smaller-text width-100 center'>" . $this->game->gameDate->format('l') . "s at " . $this->game->getGameTime() . "</p>";
echo	"<a href='/parks/" . $this->game->park->parkID . "' class='clear light smaller-text width-100 center'>" . $this->game->park->parkName . "</a>";
echo "</div>";

echo "<div class='clear larger-text width-100 light-back' id='history-current-players-container'>";
echo	"<p class='clear medium width-100 center smaller-text'>This Week:</p>";
echo	"<a href='/games/" . $this->game->gameID . "' class='largest-text medium clear width-100 center'>" . $this->game->countConfirmedPlayers() . " <span class='smaller-text medium'>players</span></a>";
echo "</div>";
$this->placeholder('narrowColumn')->captureEnd();
?>

<a href='/games/<?php echo $this->game->gameID;?>' class='left smaller-text medium'><img src='/images/global/body/single_left_arrow.png' class='back-arrow'/>Back to game</a>

<header class='clear jumbo-text darkest heavy'>
    Game Stats
</header>
<?php
	if ($this->history['totalGames'] == 0) {
		// No games yet
		echo "<p class='clear larger-text width-100 center heavy medium' style='margin-top:5em'>There have not been any games yet.  <br><span class='medium'>Please check back after a game has occurred.</span></p>";
	} else {
		// Show stats
		?>
<p class='clear medium'>
This game happens every week.  Here are the historical stats for this game.
</p>



<div class='clear' id='history-chart-header'>
    <p class='left pointer green-bold largest-text history-option'>Players</p>
    <p class='left pointer light history-option'>Success</p>
    <p class='left pointer light history-option'>Stats</p>
</div>

<div class='clear' id='history-charts-container'>
	<div class='clear' id='history-charts-inner-container'>
        <div class='clear chart players' id='history-chart'>
        </div>
        
        <div class='left chart success' id='pie-chart'>
        </div>
        
        <div class='left chart width-100 stats larger-text' id='history-stats-container'>
            <div class='clear margin-top  history-stat-container'>
                <p class='clear dark history-stat-header width-100 center' tooltip='Number of games played, successful or not'>Total Games</p>
                <p class='clear jumbo-text dark heavy width-100 center'><?php echo $this->history['totalGames'];?></p>
            </div>
            <div class='left margin-top history-stat-container'>
                <p class='clear dark history-stat-header' tooltip='Most players in any game'>Most Players</p>
                <p class='clear jumbo-text dark heavy width-100 center'><?php echo $this->history['maxPlayers'];?></p>
            </div>
            <div class='left margin-top history-stat-container'>
                <p class='clear dark history-stat-header' tooltip='Number of current subscribers'>Subscribers</p>
                <p class='clear jumbo-text dark heavy width-100 center'><?php echo $this->history['totalSubscribers'];?></p>
            </div>
            <div class='clear larger-margin-top width-100' >
                <p class='clear dark history-stat-header width-100 center' tooltip="How many games you've played in">You've played in</p>
                <p class='clear jumbo-text dark heavy width-100 center'><?php echo $this->history['userCount'];?></p>
            </div>
            
            <div class='clear larger-margin-top width-100'>
                <p class='clear dark history-stat-header-small' tooltip='These players have played in the most games.'>Most Regular Players</p>
                <?php
					$counter = 1;
					echo "<div class='clear width-33 history-most-regular-outer-container margin-top'>";
					foreach ($this->history['mostRegular'] as $player) {
						$class = '';
						if ($player['user']->userID == $this->user->userID) {
							// Is current user
							$class = 'green-bold';
						}
						$outerClass = 'clear';
						if ($counter == 11) {
							echo "</div>";
							echo "<div class='left width-33 margin-top'>";
						}
						echo "<a href='/users/" . $player['user']->userID . "' class='" . $class . " clear width-100 dark no-underline white-background animate-darker smaller-text history-most-regular-container'>
								<span class='left light history-most-regular-counter larger-margin-top'>" . $counter . ".</span>
								<img src='" . $player['user']->getProfilePic('tiny') . "' class='left'>
								<span class='inherit history-most-regular-name left larger-margin-top '>" . $player['user']->shortName . "</span> 
								<span class='left inherit larger-margin-top'>&nbsp;" . $player['count'] . "</span></a>";
						$counter++;
					}
					echo "</div>";
				?>
            </div>
            
        </div>
    </div>
</div>
<?php } ?>

<script type='text/javascript'>
chartData = [['Week', 'Players','No Game'],<?php 
			foreach ($this->history['games'] as $game) {
				if ($game->totalPlayers > $game->minPlayers) {
					// successful game, first series
					$first = $game->totalPlayers;
					$second = 0;
				} else {
					$first = 0;
					$second = $game->totalPlayers;
				}
				echo "['" . $game->gameDate->format('m/j') . "'," . $first . "," . $second . "],";
				//echo "[new Date(" . $game->gameDate->format('Y') . "," . $game->gameDate->format('m') . "," . $game->gameDate->format('d') ."), " . $first . "," . $second . "],";
			}
			?>];
			
pieChartData = [
          ['Type', 'Total'],
          ['Successful Game',<?php echo $this->history['successGames'];?> ],
          ['Failed Game', <?php echo $this->history['failedGames'];?>],
        ]
			
</script>