<img src='<?php echo $this->team->getProfilePic('large');?>' class='clear narrow-column-picture' />

<div class='clear larger-margin-top larger-text width-100'>
    <p class='clear heavy darkest width-100 center'><?php echo $this->team->teamName;?></p>
    <p class='clear darkest width-100 center smaller-text'><?php echo $this->team->sport;?> Team</p>
    <p class='clear medium width-100 center smaller-text'><?php echo $this->team->city;?></p>
</div>