<?php
$this->headTitle()->setSeparator(' | ');
/*
if (!$this->noDefaultHeadTitle) {
	// Allow override of appended Sportfast with $this->noDefaultHeadTitle = true
	$this->headTitle()->append('Sportfast');
}
*/
//$this->setEncoding('UTF-8');
//echo $this->doctype('XHTML1_TRANSITIONAL') . PHP_EOL; ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta charset='utf-8' />
<?php
		//echo $this->headMeta() . PHP_EOL;
 		echo $this->headTitle() . PHP_EOL;
 		echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/global.css') . PHP_EOL;
		
		$this->headScript()->prependFile($this->baseUrl() . '/js/global.js');
		
		if ($this->rateGame) {
		// Popup to rate users/park from last game
			$this->headScript()->prependFile($this->baseUrl() . '/js/rategame.js');
			$this->headScript()->prependFile($this->baseUrl() . '/js/rating.js');
			$this->headScript()->prependFile($this->baseUrl() . '/js/plugins/smartslider.js');
		}
		echo $this->headScript()->prependFile($this->baseUrl() . '/js/jquery-1.9.1.min.js') . PHP_EOL;
								
 ?>
</head>
<body onunload=''>
<?php
//placeholder for all absolutely placed elements
echo $this->placeholder('absolute');
echo $this->tooltip();

echo $this->placeholder('topAlert');

if ($this->topAlert) {
	// top alert to be shown, place content in animatable container
	echo "<div class='width-100 left' id='main-body-container'>";
}
//header layout
echo $this->render($this->headerLayout . '.phtml'); 

//default whiteBacking => true
if ($this->whiteBacking) {
	echo $this->render('global/whiteBack.phtml');
} else {
	echo $this->layout()->content . PHP_EOL; 
}

//footer layout
echo  $this->render('footer.phtml') . PHP_EOL; 

if ($this->topAlert) {
	// Close animatable container
	echo "</div>";
}
?>
</body>
</html>