<?php
$this->headTitle()->setSeparator(' | ');
/*
if (!$this->noDefaultHeadTitle) {
	// Allow override of appended Sportfast with $this->noDefaultHeadTitle = true
	$this->headTitle()->append('Sportfast');
}
*/
//$this->setEncoding('UTF-8');
//echo $this->doctype('XHTML1_TRANSITIONAL') . PHP_EOL; ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta charset='utf-8' />
<?php
		$this->headMeta()->setName('keywords', 'sportfast, local pickup, play sports, 
										pickup games, pickup basketball, pickup soccer, pickup football, 
										pickup ultimate frisbee, pickup volleyball, find pickup games');
		echo $this->headMeta()->setName('description', 'Find and manage recreational sports.  From pickup games to league teams, Sportfast lets you play everywhere.');
		//echo $this->headMeta() . PHP_EOL;
 		echo $this->headTitle() . PHP_EOL;
		
		$this->headLink()->prependStylesheet($this->baseUrl() . '/css/global.css') . PHP_EOL;
		
		$version = '1.126'; // VERSION FOR JS AND CSS to force refresh of cache
		
		foreach ($this->headLink() as $key => $item) {
			// Add version number to css
			if (strpos($item->href, '?') != false) {
				// Has Custom version implemented, do not add version
				continue;
			}
			$item->href .= '?' . $version;
			
		}
		
		if ($this->rateGame) {
		// Popup to rate users/park from last game
			$this->headLink()->appendStylesheet($this->baseUrl() . '/css/rategame.css?' . $version);
			$this->headScript()->prependFile($this->baseUrl() . '/js/rategame.js');
			$this->headScript()->prependFile($this->baseUrl() . '/js/objects.js');
				
		}
		
		echo $this->headLink() . PHP_EOL;
		
		$this->headScript()->prependFile($this->baseUrl() . '/js/global.js');
			
		
		foreach ($this->headScript() as $key => $item) {
			// Add version number to javascript
			if (strpos($item->attributes['src'], 'google')) {
				continue;
			}
			$item->attributes['src'] .= '?' . $version;
		}
		
		$this->headScript()->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js') . PHP_EOL;
		
		if ($this->user) {		
			// Is logged in, display mobile scripts/css	if appropriate		
 ?>
 <link rel='stylesheet' href='<?php echo $this->baseUrl() . '/css/mobile.css';?>' media='screen and (max-device-width:568px)'/>
 <meta name='viewport'  content="width=device-width, initial-scale=1.0">
 <?php
}
?>
</head>
<body onunload=''>
<?php
//placeholder for all absolutely placed elements
echo $this->placeholder('absolute');
echo $this->tooltip();

echo $this->placeholder('topalert');

if ($this->topAlert) {
	// top alert to be shown, place content in animatable container
	echo "<div class='width-100 left' id='main-body-container'>";
}
//header layout
echo $this->render($this->headerLayout . '.phtml'); 

//default whiteBacking => true
if ($this->whiteBacking) {
	echo $this->render('global/whiteBack.phtml');
} else {
	echo $this->layout()->content . PHP_EOL; 
}

//footer layout
echo  $this->render('footer.phtml') . PHP_EOL; 

if ($this->topAlert) {
	// Close animatable container
	echo "</div>";
}
?>

<script>
// Google Analytics
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-26235588-2', 'sportfast.com');
  ga('send', 'pageview');

</script>
<?php 

echo $this->headScript();

if ($this->user) {
	// Is logged in, test for mobile and include appropriate scripts
	echo "<script>
	(function() {
		
		if (isMobile()) {

			var jqueryMobile = document.createElement('script');
			jqueryMobile.src = '" .  $this->baseUrl() . "/js/plugins/jquerymobile/jquery.mobile.custom.min.js';
			$('body').append(jqueryMobile);
			
			var mobileJs = document.createElement('script');
			mobileJs.src = '" .  $this->baseUrl() . "/js/mobile.js';
			$('body').append(mobileJs);
			
		}
	})();
	</script>";
}
/*
<script src='" .  $this->baseUrl() . "/js/plugins/jquerymobile/jquery.mobile.custom.min.js' media='screen and (max-device-width:568px)'></script>
	 		<script src='" .  $this->baseUrl() . "/js/mobile.js' media='screen and (max-device-width:568px)'></script>
	 		*/
?>
</body>
</html>