<?php
//$this->headTitle()->setSeparator(' | ');
//$this->headTitle('Sportup');
echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php
		echo $this->headMeta() . PHP_EOL;
 		echo $this->headTitle() . PHP_EOL;
 		echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/global.css') . PHP_EOL;
		echo $this->headScript()->prependFile($this->baseUrl() . '/js/global.js')
								->prependFile($this->baseUrl() . '/js/jquery-1.8.min.js') . PHP_EOL;
								
 ?>
</head>
<body>
<?php echo $this->render('header/tall.phtml'); ?>
<div class='centered-body'>
	<?php echo $this->layout()->content . PHP_EOL; ?>
</div>
<?php echo  $this->render('footer.phtml') . PHP_EOL; ?>
</body>
</html>