<?php
/* 
* controller => index
* action => index
*/
//change title of homepage to Sportup - Compete Everywhere
$this->headTitle()->exchangeArray(array('Sportup','Compete Everywhere'));


if (!$this->loggedIn) {
	// Not logged in, display non-member homepage
	$this->headLink()->prependStylesheet($this->baseUrl() . '/css/homepage.css');
	$this->headScript()->prependFile($this->baseUrl() . '/js/homepage.js');
	echo $this->homepage(); //$this->getHelper('homepage')->testFunction();
} else {
	// Logged in, display member homepage
	$this->headLink()->prependStylesheet($this->baseUrl() . '/css/member.css');
	$this->headScript()->prependFile($this->baseUrl() . '/js/member.js');
	echo $this->memberHomepage();
}


?>
