<?php
/* 
* controller => index
* action => index
*/
$this->headTitle('Sportup | Compete Everywhere');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/homepage.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/homepage.js');

/* to be filled with controller test against login cookie */
$loginTest = false;
if (!$loginTest) {
	/* if not logged in, show homepage from view helper */
	echo $this->homepage(); //$this->getHelper('homepage')->testFunction();
} else {
	/* else show memberHomepage from view helper*/
	echo 'no test';
}

?>
