<?php
/* 
* controller => index
* action => index
*/
//change title of homepage to Sportfast - Compete Everywhere
$this->headTitle()->exchangeArray(array('Sportfast','Play Everywhere'));


if (!$this->loggedIn) {
	// Not logged in, display non-member homepage
	$this->headLink()->prependStylesheet($this->baseUrl() . '/css/homepage.css');
	$this->headScript()->prependFile($this->baseUrl() . '/js/homepage.js');
	echo $this->homepage(); //$this->getHelper('homepage')->testFunction();
} else {
	// Logged in, display member homepage
	$this->headLink()->prependStylesheet($this->baseUrl() . '/css/member.css');
	$this->headScript()->prependFile($this->baseUrl() . '/js/member.js');
	$this->headScript()->prependFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyAhxSMQ-WQux2nzTW4dBoKmpfGHVQOk7r8&sensor=false');
	echo $this->memberhomepage();
	?>
    <script type='text/javascript'>
	<?php 
	   if (!empty($this->matches)) {
		   // Matches exist
		   ?>
		gmapMarkers = [		<?php
								 foreach ($this->matches as $match) {
									 if ($match instanceof Application_Model_Game) {
										 // Is game, create marker on map
										 $location = $match->getPark()->getLocation();
										 echo '[' . $location->latitude . ',' . $location->longitude . '],';
									 }
								 }?>
					  ]
	<?php } ?>
					
		userLocation = [<?php echo '"' . $this->user->getLocation()->latitude . '","' . $this->user->getLocation()->longitude . '"';?>];
	</script> 
    <?php
}


?>
