<div class='width-100 profile-options-outer-container'>
	<div class='profile-options-inner-container white-background left width-100'>
    	<?php
			if (isset($this->guests)) {
				echo "<div class='right margin-top'>";
				echo "<p class='medium smaller-text left margin-top'>Guests</p>";
				echo "<select class='smaller-text medium' id='game-plus'>";
        
                    for ($i = 0; $i < 3; $i++) {
						if ($i > ($this->game->rosterLimit - $this->confirmedPlayers)) {
							continue;
						}
                        $selected = '';
                        if ($this->guests == $i) {
                            $selected = 'selected';
                        }
                        echo "<option " . $selected . ">" . $i . "</option>";
                    }
               
				echo "</select>";
				echo "</div>";
			}
		?>
    	<div class='profile-options-container left width-100'>
    	<?php
			$class = 'profile-option-container';
			if (count($this->options) > 7) {
				$class = 'profile-option-container-narrow';
			}
			
			foreach (array_reverse($this->options) as $option) {
				if (isset($option['href'])) {
					// Is link
					$href = " href='" . $option['href'] . "' ";
					$tag = "a";
				} else {
					$href = " ";
					$tag = "div";
				}
				
				$tooltip = '';
				if (isset($option['tooltip'])) {
					$tooltip = 'tooltip="' . $option['tooltip'] . '"';
				}
				
				
				
				echo "<" . $tag . " " . $href . " id='profile-option-" . $option['img'] . "' class='right " . $class . " white-background animate-darker pointer' " . $tooltip . ">
							<div class='left width-100'>
								<img src='/images/games/icons/" . $option['img'] . ".png' class='profile-options-img auto-center'  />
							</div>
							<p class='medium left heavy width-100 center smaller-text'>" . strtoupper($option['text']) . "</p>
						</" . $tag . ">
						";
			}
		?>
        </div>
        <p class='profile-options-button pointer clear-right medium center animate-darker'>show options</p>
	</div>
</div>