<?php
/** 
 * controller => find
 * action => parks
 */
$this->headTitle('Find Parks');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/find.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/find.js');
$this->headScript()->prependFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyAhxSMQ-WQux2nzTW4dBoKmpfGHVQOk7r8&sensor=false');

?>


<?php
$this->placeholder('narrowColumn')->captureStart();
	echo "<div id='gmap' class='narrow-column-picture'></div>";
	echo "<p class='clear larger-margin-top white arial bold larger-text width-100 center dark-back'>FILTERS</p>";
	echo $this->narrowcolumnsection()->start(array('title' => 'Courts And Fields'));
	echo $this->checkbox->setName('courtAny')
						->setAttribs(array('text' =>'Any',
										   'checked' => 'checked'));
	echo $this->checkbox->setName('courtSpecific')
						->setAttribs(array('text' =>'Specific',
										   'checked' => false));
	
	$counter = 0;
	echo "<div class='hidden larger-margin-top clear width-100' id='court-specific'>";
	foreach ($this->courts as $court) {
		$class = 'selectable-text selectable-text-one light pointer narrow-sport ';
		if ($counter % 2 == 0) {
			// even
			$class .= ' clear';
		} else {
			$class .= ' right';
		}
		
		if ($counter == 0) {
			$class .= ' green-bold';
		}
		
		echo	"<p class='" . $class . "'>" . ucwords($court) . "</p>";
		$counter++;
	}
	echo "</div>";
	echo $this->narrowcolumnsection()->end();
	
	
	
	echo $this->narrowcolumnsection()->start(array('title' => 'Stash'));
	echo $this->checkbox->setName('stashAny')
						->setAttribs(array('text' =>'Any',
										   'checked' => 'checked'));
	echo $this->checkbox->setName('stashYes')
						->setAttribs(array('text' =>'Has stash',
										   'checked' => false));
	echo $this->checkbox->setName('stashNo')
						->setAttribs(array('text' =>'No stash',
										   'checked' => false));
	echo $this->narrowcolumnsection()->end();
	
	
	echo $this->narrowcolumnsection()->start(array('title' => 'Type'));
	echo $this->checkbox->setName('typeAny')
						->setAttribs(array('text' =>'Any',
										   'checked' => 'checked'));
	echo $this->checkbox->setName('typePark')
						->setAttribs(array('text' =>'Park',
										   'checked' => false));
	echo $this->checkbox->setName('typeSchool')
						->setAttribs(array('text' =>'School',
										   'checked' => false));
	echo $this->checkbox->setName('typeGym')
						->setAttribs(array('text' =>'Gym',
										   'checked' => false));
	echo $this->narrowcolumnsection()->end();
			
$this->placeholder('narrowColumn')->captureEnd();

?>

<p class='left darkest heavy indent'><span class='inherit' id='find-num-results'><?php echo $this->numMatches;?></span> parks found</p>
<?php
$content  = "<div class='right' id='find-looking-container'>";
$content .=		"<p class='left darkest heavy'>Looking for:</p>";
$content .= 	"<div class='left indent'>" . $this->lookingFor . "</div>";
$content .= "</div>";
$content .= "<div class='left' id='find-order-by'>";
$content .= 	"<p class='light left'>Order by:</p>";
$content .= 	"<p class='light left pointer selectable-text selectable-text-one'>Rating</p>";
$content .= 	"<p class='light left pointer selectable-text selectable-text-one green-bold'>Distance</p>";
$content .= "</div>";
echo $this->partial('partials/global/sectionHeaderBold.phtml',array('title'   => 'Results',
																	'content' => $content));

echo $this->find()->createPagination(false);
echo "<div class='find-results-outer-container left width-100' id='find-results-outer-container'>";
echo "<div class='find-results-outer-inner-container left width-100' id='find-results-inner-container'>";
echo $this->find()->loopMatches($this->matches, 'park');
echo "</div></div>";
echo $this->find()->createPagination(true);

echo "<img src='/images/global/loading.gif' id='loading' class='hidden'/>";

?>

<script type='text/javascript'>
	var gmapMarkers = [];
	<?php 
	   if (!empty($this->matches)) {
		   // Matches exist
		   ?>
		gmapMarkers = [		<?php
								 $counter = 0;
								 foreach ($this->matches as $match) {
									 if ($match instanceof Application_Model_Park) {
										 // Is park, create marker on map
										 $output = '';
										 if ($counter != 0) {
											 $output .= ',';
										 }
										 $location = $match->getLocation();
										
										 $output .= '[' . $location->latitude . ',' . $location->longitude . ']';
										 
										 echo $output;
										 $counter++;
										 
									 }
								 }?>
					  ]
	<?php } ?>
					
		var userLocation = [<?php echo '"' . $this->user->getLocation()->latitude . '","' . $this->user->getLocation()->longitude . '"';?>];
</script> 
