<?php
/** 
 * controller => users
 * action => index
 */
$this->headTitle($this->currentUser->fullName);
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/user.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/profile.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/user.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/profile.js');
?>


<?php
if ($this->userNotFound) {
	echo "<p class='clear width-100 center heavy jumbo-text darkest'>User Not Found</p>";
	echo "<p class='clear width-100 center largest-text darkest'>This user does not appear to exist.</p>";
	echo "<div class='clear width-100'><a href='/' class='center heavy button auto-center' style='width:9em;margin-top:.5em;'>Back to homepage</a></div>";
	return;
}

$this->placeholder('absolute')->captureStart();

echo $this->partial('partials/global/alertBack.phtml');
echo $this->alert()->confirmAlert();


$this->placeholder('absolute')->captureEnd();


// Narrow right column
$this->placeholder('narrowColumn')->captureStart();
echo "<img src='" . $this->currentUser->getProfilePic('large') . "' class='narrow-column-picture dropshadow'/>";

echo "<div class='user-narrow-info-container clear'>";
echo 	"<p class='clear darkest'>" . $this->currentUser->age . " years old</p>";
echo 	"<p class='clear darkest'>" . $this->currentUser->getSexFull() . "</p>";
echo 	"<p class='clear darkest'>" . $this->currentUser->getHeightInFeet() . "</p>";
echo "</div>";

$sections = array('players', 'teams');

echo $this->narrowteamsection($this->currentUser, $sections);

echo "<div class='width-100 narrow-column-calendar-container clear'>";
echo $this->calendar()->createCalendar($this->currentUser->games->games, true);
echo "</div>";

$this->placeholder('narrowColumn')->captureEnd();

?>
<span id='user-details'
		actingUserID='<?php echo $this->user->userID;?>'
	  	receivingUserID='<?php echo $this->currentUser->userID;?>'>
</span>


<header class='clear user-name-container'>
	<p class='user-name heavy darkest clear'>
    	<?php echo $this->currentUser->shortName;?>
	</p>
    <div class='user-city-container clear'>
        <p class='light clear'>
            <?php echo $this->currentUser->city->city . ", " . $this->currentUser->city->state;?>
        </p>    
        <p class='light clear'>
            Last active <?php echo $this->currentUser->getLastActiveFromNow();?>
        </p> 
    </div>
</header>

<div id='profile-buttons-container'>
	<?php
	if ($this->currentUser->userID != $this->user->userID) {
		// Not current user
	?>
    <a href='/users/<?php echo $this->user->userID;?>/group/<?php echo $this->currentUser->userID;?>' class='button right' id='user-message' onclick='window.location = this.href;'> <!-- strange bug in jQuery plugin section of global.js that prevents clicking the message button.  force redirect with inline onclick -->
    	Message
    </a>
    <?php
	
		if (!$this->user->players->userExists($this->currentUser->userID)) {
			// user is not already a friend
			
			if ($this->friendRequest) {
				$text = 'Request pending';
				$class = 'clicked';
				$tooltip = 'There is a player request pending.';
			} else {
				$text = 'Player Request';
				$class = '';
				$tooltip = "Connected players play together often. Connecting makes it easier to see each other's upcoming games.";
			}
			?>
			<p class='button right profile-buttons-margin-right <?php echo $class;?>' id='user-player-request' tooltip="<?php echo $tooltip;?>">
				<?php echo $text;?>
			</p>
    <?php } else {?>
    		<p class='right medium smaller-text pointer action profile-buttons-margin-right' id='user-player-cancel-request' tooltip='You are currently connected with this player.  Remove them?'>
            	Remove Player
            </p>
    <?php }
		
			echo "<div class='clear-right larger-margin-top'>" . $this->inviteButton . "</div>";
		}
	?>
</div>

<div id='user-sports-container' class='clear'>
	<?php
		echo $this->profilesportsections()->start($this->currentUser->sports, $this->selectedSport);
		$lowerOutput = '';
		$count = 0;
		foreach ($this->currentUser->sports as $sport) {
			
			$class = $tabClass = '';
			if ($this->selectedSport) {
				// Sport selected in controller
				if (strtolower($sport->sport) == strtolower($this->selectedSport)) {
					$class = 'user-sport-container-selected';
					$tabClass = 'user-sport-selected';
				}
			} elseif ($count == 0) {
				// First sport, show box
				$class = 'user-sport-container-selected';
				$tabClass = 'user-sport-selected';
			}
			
			$lowerOutput .= "<div class='user-sport-container rounded-corners light-back " . $class . " dropshadow-bottom'>";
			$lowerOutput .= 	"<div class='user-sport-left-container'>";
			$lowerOutput .= 		"<p class='clear darkest'>";
			
			// Positions
			$counter = 0;
			if ($sport->hasValue('positions')) {
				foreach ($sport->positions as $position) {
					$lowerOutput .= $position->positionName;
					if ($counter !== count($sport->positions) - 1) {
						$lowerOutput .= '/';
					}
					$counter++;
				}
			}
			
			// Best skill
			$lowerOutput .= 		"<p class='darkest clear'>";
			
			if ($firstSkill = $sport->ratings->getBestSkill(0)) {
				$lowerOutput .= "<span class='darkest largest-text'>" . $firstSkill . "</span>";
			}
			if ($secondSkill = $sport->ratings->getBestSkill(1)) { 
				$lowerOutput .= ", <span class='darkest larger-text'>" . $secondSkill . "</span>";
			}
			if ($thirdSkill = $sport->ratings->getBestSkill(2)) { 
				$lowerOutput .= ", <span class='darkest'>" . $thirdSkill . "</span>";
			}
			
			if (!$firstSkill) {
				// No skill was found, display none
				$lowerOutput .= "<span class='medium larger-text'>No skills have been rated.</span>";
			}
			
			// Wants to play ??
			$lowerOutput .= 		"<div class='clear user-sport-want-outer-container'>";
			$lowerOutput .= 			"<p class='clear dark user-sport-want-looking'> Looking for:</p>";
			$lowerOutput .= 			"<div class='user-sport-want-inner-container left'>";
		
			foreach ($sport->formats as $format) {
				$lowerOutput .=				"<p class='darkest clear'>" . ucwords($format->format) . "</p>";
			}

			// Array of types, display
			$typeSuffixes = '';
			$typeSuffixArray = array();
			$typeNameArray = array();
			foreach ($sport->types as $type) {
				if (strtolower($type->typeName) == 'pickup') {
					// Type has not been displayed yet
					continue;
					
				}
				
				$lowerOutput  .=			"<p class='medium clear user-sport-type'>" . ucwords($type->typeName) . " " . ucwords($type->typeSuffix) . "</p>";
				/*if (in_array($type->typeSuffix, $typeSuffixArray)) {
					// Suffix was already used
					continue;
				}*/
				//$typeSuffixes .= 			"<p class='medium clear user-sport-typeSuffix'>" . ucwords($type->typeSuffix) . "</p>";
				//$typeSuffixArray[] = $type->typeSuffix;
				//$typeNameArray[] = $type->typeName;
			}
			$lowerOutput .= $typeSuffixes;
			
			$lowerOutput .=				"</div>";
			$lowerOutput .=			"</div>";
			$lowerOutput .=		"</div>";	
			// Ratings
			
			$topRatings = $this->currentUser->getSport(strtolower($sport->sport))->sportRatings->getTopSkills();
			
			$ratings      = array('avgSkill' => '');
			for ($i = 0; $i < count($topRatings); $i++) {
				$ratings[$topRatings[$i]->ing] = $topRatings[$i];
			}
						
			$lowerOutput .= 	"<div class='user-sport-right-container'>";
			$lowerOutput .=			"<p class='medium smaller-text action right why-ratings pointer'>What are these ratings?</p>";
			$lowerOutput .=			"<a href='/users/" . $this->currentUser->userID . "/ratings/" . strtolower($sport->sport) . "' class='user-sport-rating-container'>";
			$counter = 1;
			
			foreach ($ratings as $rating => $abbrev) {
				
				if ($counter == 1) {
					$val = $sport->avgSkill;
				} else {
					$val = $abbrev->value;
				}
				
				$class = 'left larger-text user-rating-container';
				$label = "<p class='clear width-100 center white smaller-text'>" . $rating . "</p>";
				$value = "<p class='clear width-100 center inherit'>" . $val . "</p>";
				
				if ($counter == 1) {
					$class = 'clear width-100 jumbo-text heavy user-rating-container-first';
					$label = '';
				} elseif ($counter == count($ratings)) {
					// Last one
					$class .= ' user-rating-container-last';
				}
				$lowerOutput .= "<div class='center medium-background white " . $class . "'>" . $label . $value . "</div>";
				
				$counter++;
			}
			
			$numRatings   = (!$sport->ratings->hasValue('ratings') ? 0 : count($sport->ratings->ratings));
			$str = 'ratings';
			if ($numRatings == 1) {
				$str = 'rating';
			}
			$lowerOutput .= 		"</a>";
			$lowerOutput .=				"<a href='/users/" . $this->currentUser->userID . "/ratings/" . strtolower($sport->sport) . "' class='dark clear-right user-sport-num-ratings'>" 
										. $numRatings . " " . $str
										. "</a>";			
			$lowerOutput .= 	"</div>";
			
			if ($this->currentUser->players->exists($this->user->userID) || $this->currentUser->userID == $this->user->userID) {
				// Are friends, let see availability
				$lowerOutput .= "<div class='clear user-availability-show'><img src='/images/global/body/down_arrow.png' class='left margin-top'/><p class='medium left pointer indent user-show-availability'>show availability</p></div>";
				$lowerOutput .= "<div class='clear user-availability-hide hidden'><img src='/images/global/body/up_arrow.png' class='left margin-top'/><p class='medium left pointer indent user-show-availability'>hide availability</p></div>";
				$lowerOutput .= $this->availabilitycalendar()->create($sport->sport, $sport);
			}
				
			$lowerOutput .= "</div>";
			
			$count++;
		}
	?>
    
</div>

<?php
	// Sports section
	echo $lowerOutput;
	
	
	
	if ($this->currentUser->games->hasValue('games')) {
		
		$output = $this->partial('partials/global/sectionHeaderBold.phtml',array('title'   => 'Upcoming Games'));
		
		$games = $this->currentUser->games->getGamesByDate();
		
		$success = false;
		for ($i = 0; $i < 3; $i++) {
			if (!isset($games[$i])) {
				continue;
			}

			if ($games[$i]->confirmed != 1) {
					// Not attending upcoming game, do not show
					continue;
				}
			if (isset($games[$i])) {
				$success = true;
				$output .= $this->find()->createGame($games[$i]);
			}
		}
		
		if ($success) {
			// There is actually a game
			echo $output;
		}
	}
	
	// Activity section
	echo "<div id='user-activities-container'>";
	foreach ($this->activities as $activity) {
		echo $this->memberHomepage->createNotification($activity, 'small');
	}
	echo "</div>";
?>

