<?php
/** 
 * controller => users
 * action => ratings
 */
$this->headTitle($this->currentUser->shortName . ' Ratings');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/rating.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/profile.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/rating.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/profile.js');
$this->headScript()->prependFile('https://www.google.com/jsapi');
?>


<?php
// Narrow right column
$this->placeholder('narrowColumn')->captureStart();
echo "<img src='" . $this->currentUser->getProfilePic('large') . "' class='narrow-column-picture dropshadow'/>";

echo "<p class='width-100 center dark clear larger-margin-top'>" . $this->sport->sport . "</p>";
echo "<div class='width-100 clear center green bold jumbo-text'>" . $this->sport->getOverall() . "</div>";
echo "<div class='width-100 clear'>";

foreach ($this->ratingOrder as $rating => $label) {
	// Create individual rating breakdown
	echo "<div class='rating-individual-container'>";
	echo 	"<p class='green smaller-text width-100 center clear rating-label'>" . $label . "</p>";
	echo 	"<p class='green bold larger-text width-100 center clear'>" . $this->sport->$rating . "</p>";
	echo "</div>";
}

echo "</div>";


// Top skills
echo $this->narrowcolumnsection()->start(array('title' => 'Top Skills'));

echo "<div class='clear width-100'>";
foreach ($this->ratings->getBestSkills() as $skiller => $count) {
	echo "<p class='clear dark'>" . ucwords($skiller) . "</p>";
	echo "<p class='right light'>" . $count . "</p>";
}
echo "</div>";

echo $this->narrowcolumnsection()->end();

// Stats
echo $this->narrowcolumnsection()->start(array('title' => $this->sport->sport . ' Stats'));

echo "<p class='clear light'>Games played:</p>";
echo "<p class='right dark'>" . $this->sportStats['totalGames'] . "</p>";

echo "<p class='clear light margin-top' tooltip='Total number of " . strtolower($this->sport->sport) . " ratings given.'>
		Ratings given:
	  </p>";
echo "<p class='right dark margin-top'>" . $this->sportStats['totalRatings'] . "</p>";

echo "<p class='clear light margin-top' tooltip='Total number of different players you have played " . strtolower($this->sport->sport) . " with.'>
		Different players:
	  </p>";
echo "<p class='right dark margin-top'>" . $this->sportStats['totalPlayers'] . "</p>";


echo "<p class='clear light margin-top' tooltip='You have played the most " . strtolower($this->sport->sport) . " games with these players.'>Most games with:</p>";
foreach ($this->sportStats['mostPlayer'] as $player) {

	if (empty($player['name'])) {
		// No most played with player
		$name = 'None';
	} else {
		$name = $player['name'] . " <span class='right dark'>" . $player['times'] . "</span>";
	}
	
	echo "<a href='/users/" . $player['userID'] . "' class='clear width-100 dark'>" . $name . "</a>";
}

echo "<p class='clear light margin-top' tooltip='Estimated total calories burned'>
		Calories burned:
	  </p>";
echo "<p class='right dark margin-top'>" . $this->sportStats['calories'] . "</p>";	 

echo "<p class='clear light margin-top' tooltip='Avg calories burned per week'>
		Calories/week:
	  </p>";
echo "<p class='right dark margin-top'>" . $this->sportStats['caloriesPerWeek'] . "</p>"; 

echo $this->narrowcolumnsection()->end();

$this->placeholder('narrowColumn')->captureEnd();

?>

<a href='<?php echo $this->baseURI;?>' class='left smaller-text medium'><img src='/images/global/body/single_left_arrow.png' class='back-arrow'/>Back to profile</a>


<div class='clear width-100' id='chart-container'>
	<div class='clear width-100'>
    	<?php
		$ratings = array('Overall', 'Skill', 'Sportsmanship');
		$counter = 0;
		foreach ($ratings as $rating) {
			$class = 'light rating-chart-option';
			if ($counter == 0) {
				$class = 'green-bold largest-text rating-chart-option';
			}
			echo "<p class='left pointer " . $class . "'>" . $rating . "</p>";
			$counter++;
		}
		?>
    <div class='right larger-text' id='rating-sports'><?php echo $this->sportButton;?></div>
    
    </div>
    <div id='chart' class='left width-100' style='height: 250px'>
    </div>
</div>

<header class='width-100 left'>
	<p class='jumbo-text heavy darkest left larger-margin-top'><?php echo $this->numRatings . ' ' . strtolower($this->sport->sport) . ($this->numRatings == 1 ? ' rating' : ' ratings');?></p>
    <!--<p class='left largest-text darkest profile-header-sub'>for <div class='left larger-text' id='rating-sports'><?php echo $this->sportButton;?></div> </p>-->
</header>


<div class='width-100 clear ratings-container'>
	<?php
	echo $this->ratings()->loopUserRatings($this->ratings->getAll());
	
	?>
</div>

<script type='text/javascript'>
var sportID = '<?php echo $this->sport->sportID;?>';
var userID = '<?php echo $this->currentUser->userID;?>';
var chartData = {};
<?php
	foreach ($ratings as $rating) {
		
		echo '
		chartData["' . strtolower($rating) . '"] = [["Month", "' . $rating . '"],';
		$valuesName = 'chartRatings' . $rating;
		foreach ($this->$valuesName as $month) {
			if ($month['value'] == 0) {
				$month['value'] = 'null';
			}

			echo "[new Date(" . $month['year'] . "," . $month['month'] . "," . $month['day'] . "), " . $month['value'] . "], ";
		}
		
		echo '];';
	}
?>
		
</script>