<?php
/** 
 * controller => users
 * action => teams
 */
$this->headTitle($this->currentUser->shortName . "'s Teams");
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/user.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/user.js');
?>

<?php
$this->placeholder('narrowColumn')->captureStart();

echo "<img src='" . $this->currentUser->getProfilePic('large') . "' class='left narrow-column-picture dropshadow rounded-corners'/>";

$this->placeholder('narrowColumn')->captureEnd();
?>

<header class='jumbo-text darkest heavy clear'>
<?php echo $this->currentUser->shortName . "'s Teams";?>
</header>

<?php
echo "<div class='width-100 larger-margin-top clear'>";
foreach ($this->currentUser->teams->getAll() as $team) {
	echo $this->find()->createTeam($team);
}
echo "</div>";