<?php
/* 
* controller => users
* action => upload
*/

$this->headTitle('Upload Image');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/upload.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/plugins/jcrop.min.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/upload.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/plugins/jcrop.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/plugins/jform.js');
?>

<?php
echo $this->placeholder('absolute')->captureStart();

	echo $this->partial('partials/global/alertBack.phtml');
	echo $this->alert()->confirmAlert();
	
echo $this->placeholder('absolute')->captureEnd();
?>


<header class='left jumbo-text darkest heavy'>
	Upload Profile Picture
</header>

<p class='right dark why-profile pointer' id='upload-why-profile'>
        	Why do I need a profile picture?
        </p>

<?php
if ($this->pictureRequired) {
	// Tried to join game without profile pic, show that pic is required
	echo "<p class='larger-text white left heavy dark-red-back width-100 center' id='upload-required'>Profile Picture required to " . $this->pictureRequired . " game.  Please upload one.</p>";
}
?>
<div id='upload-container' class='clear'>
    <img class='clear signup-import-alert-img' id='signup-import-alert-img' src='/images/global/profile/xl/default.jpg'/>
    <div class='signup-import-alert-text-container'>
        <p class='medium clear' id='signup-import-alert-guidelines-header'>Profile pictures should be:</p>
        <ul class='green heavy' id='signup-import-alert-guidelines'>
            
            <li>easily recognizable</li>
            <li>a clear shot of your face</li>
        </ul>
        <div class='button import-button' id='signup-import-alert-button'>
            Choose Photo
            <form action="/ajax/upload-temp-picture" enctype="multipart/form-data" name='file_upload' id='upload-profile-pic'>
                <input type='file' name='profilePic' id='profilePic' accept="image/*"/>
            </form>
        </div>
        <?php
		
			if ($this->user->hasProfilePic()) {
				?>
               
                    <div class='clear width-100 center smaller-text action margin-top medium pointer' id='upload-delete-picture'>delete picture</div>
        <?php }?>
        <div id='signup-alert-rotate-container' class='clear width-100 clear'>
            <img src='/images/global/img_upload/rotate_left.png' class='clear signup-alert-rotate pointer hidden' id='signup-alert-rotate-left' tooltip='Rotate image left'/>
            <img src='/images/global/img_upload/rotate_right.png' class='right signup-alert-rotate pointer hidden' id='signup-alert-rotate-right' tooltip='Rotate image right'/>
        </div>
        <p class='medium' id='signup-import-alert-warning'>
            If players cannot recognize you by your picture, you <span class='heavy medium'>will not receive any ratings.</span>
        </p>
        
        
        <div class='width-100 clear' id='signup-import-alert-accept-container'>
    	<p class='red smaller-text right pointer hidden' id='signup-import-alert-cancel'>cancel</p>
        <div class='button green-button larger-text right hidden' id='signup-import-alert-accept'>
            Accept
        </div>
        
    </div>
        
    </div>
</div>

<?php
	if ($this->goToURL) {
		// send user back to referring address
?>
<script type='text/javascript'>
	goToURL = "<?php echo $this->goToURL;?>";
</script>
<?php
	}
?>