<?php
	if ($this->rateGame) {
		// Popup to rate users/park from last game		
		echo $this->alert()->ratingAlert($this->rateGame);
		echo $this->partial('partials/global/alertBack.phtml');
		
		/*
       	echo "<script type='text/javascript'>";
	   	$counter = 0;
		foreach ($this->rateGameDescriptions as $rating) {
			echo "sliderSkillValues[" . $counter . "]['description'] = '" . $rating['ratingDescription'] . "';";
			$counter++;
		}
		echo "</script>";
		*/
		
	}
?>

<script>
	// Used to determine if user is logged in for global.js (to run notification polling)
	var loggedIn = "<?php echo date('Y-m-d H:i:s');?>";

</script>


<!--[if lte IE 8]>
<style>
#feedback {
	display:none !important;
}
</style>
<![endif]-->
<a href='/contact' id='feedback' class='button heavy'>
Feedback
</a>


<div class='header-bar' id='header-bar-short'>
</div>
<div class='dropshadow-bottom' id='header-bar-location'>
</div>

<div class='dropshadow white-back' id='notifications-container'>

<?php
	
	if (!$this->user->notifications->hasValue('read') && !$this->user->notifications->hasValue('unread')) {
		// No messages
		echo "<p class='notification-container medium left'>You have no notifications</p>";
	}
	
	$sections = array('unread', 'read');
	foreach ($sections as $section) {
		
		$class = '';
		if ($section == 'unread') {
			$class = 'light-back';
		}
		foreach ($this->user->notifications->$section as $notification) {
			$buttons = '';
			$remove = '';
			if (!is_object($notification)) {
				continue;
			}
			if ($notification->hasValue('actionRequired')) {	
				$buttons = "<div class='notification-button-container clear-right' notificationLogID='" . $notification->notificationLogID . "' type='" . $notification->type . "' action='" . $notification->action . "'>";
				$buttons .= "<p class='button notification-action-button'>Confirm</p>";
				$buttons .= "<p class='button notification-action-button notification-action-button-second'>Decline</p>";
				$buttons .= "</div>";
				$remove = "<p class='light larger-text right notification-remove' tooltip='Delete'>x</p>";
			} elseif ($notification->hasValue('joinOption')) {
				$buttons = "<div class='notification-button-container clear-right' notificationLogID='" . $notification->notificationLogID . "' type='" . $notification->type . "' action='" . $notification->action . "'>";
				$buttons .= "<p class='button notification-join'>Join</p>";
				$buttons .= "</div>";
				$remove = "<p class='light larger-text right notification-remove' tooltip='Delete'>x</p>";
			}
			
			
			if ($notification->isSports()) {
				// Special case for smaller sports pictures
				$pictureClass = 'notification-picture-sports';
			} else {
				$pictureClass = 'notification-picture';
			}
			
			echo "<a href='" . $notification->getFormattedUrl() . "' class='notification-container " . $class . " pointer' notificationLogID = '" . $notification->notificationLogID . "'>" 
				 . "<div class='notification-text-picture-container'>"
					 . "<img src='" . $notification->getPicture() . "' class='" . $pictureClass . "' />"
					 . "<span class='notification-text'>" . $notification->getFormattedText() . "</span>"
					 . $remove
					 . $buttons
				 . "</div>"
				 . "<span class='notification-time-subscript light'>" . $notification->getTimeFromNow() . "</span>"
				 . "</a>";
			
		}
	}
?>
</div>

<div id='city-change-container' class='medium-background dropshadow'>
	<?php echo $this->changeCityForm->changeCity;?>
    <p class='lighter smaller-text center width-100 clear' id='city-change-or'>or</p>
    <?php echo $this->changeCityForm->changeZipcode;?>
    <p id='city-change-reset' class='underline lighter smaller-text pointer '>reset to home</p>
    <div id='city-change-results-container'>
    </div>
</div>

<div id='header-search-results-container'>
</div>

<div id='confirm-alert' class='heavy white dropshadow center'>
Request sent
</div>
	
    <nav class='mobile'>
    
    	
        <div class='dropdown' data-target='#dropdown-container'></div>
        <div id='logo-container' class='left'><a href='/'><img src='/images/mobile/nav/logo.png' class='logo auto-center' /></a></div>
        <div class='notification' data-target='#notifications-container'>
        
        	<div class='green-back nav-notification-indicator-container'>
                <p class='white centered arial nav-notification-indicator'><?php echo $this->user->notifications->countUnread();?></p>
            </div>
        
        </div>
        
        <div class='clear dark-back dropshadow' id='dropdown-container'>
        	
            <ul class='clear width-100'>
            	<?php
					$class = 'darkest heavy';
				?>
            	<a href='/users/<?php echo $this->user->userID;?>'><li><img src='<?php echo $this->user->getProfilePic('tiny');?>' class='left' /><p class='<?php echo $class;?> name left indent'><?php echo $this->user->shortName;?></p></li></a>
                <a href='/'><li><p class='<?php echo $class;?>'>Home</p></li></a>
                <a href='/users/<?php echo $this->user->userID;?>/settings'><li><p class='<?php echo $class;?>'>Account Settings</p></li></a>
                <a href='/login/logout'><li><p class='<?php echo $class;?>'>Logout</p></li></a>
            
            </ul>
            
        </div>
        
    </nav>

    <div class='centered-body body-wrapper'>
    	<div class='header-nav-container-short'>
        	<a href='/'><img src='/images/global/logo/small_beta.png' class='left'/> </a>
            
            <a href='/'><img src='/images/global/header/home_icon.png' id='header-home-icon' /></a>
            
            <div class='nav-back-short nav-dropdown' id='nav-back-find'>
                <a href='/find' class='nav nav-out-short lightest' id='nav-find'>
                <p class='nav-dropdown-text'>FIND</p>
                
                </a>
                
                <div class='dropdown-back-outer' id='nav-dropdown-outer-find'>
                    <div class='dropdown-back-inner' id='nav-dropdown-inner-find'>
                        <?php 
							$find = array('games','teams','players','parks');
							foreach ($find as $section) {
								echo $this->partial('partials/global/headerDropdownOption.phtml', array('controller' => 'find','section' => $section));
							}
						?>
                    </div>
                </div>
            </div>
            
            <div class='nav-back-short nav-dropdown' id='nav-back-create'>
                <a href='/create' class='nav nav-out-short lightest' id='nav-create'>
                	<p class='nav-dropdown-text'>CREATE</p>
                     
                </a>
                                                
                <div class='dropdown-back-outer' id='nav-dropdown-outer-create'>
                    <div class='dropdown-back-inner' id='nav-dropdown-inner-create'>
                         <?php 
							$create = array('game','team');
							foreach ($create as $section) {
								echo $this->partial('partials/global/headerDropdownOption.phtml', array('controller' => 'create','section' => $section));
							}
						?>
                    </div>
                </div>
            </div>
            
            <?php
				echo $this->headerSearchForm;
			?>
            
            <div class='nav-click-dropdown nav-back-short' id='nav-back-cog'>
            	<div id='nav-cog'>
                    <img src="/images/global/header/cog.png" class='pointer nav-cog-background'/>
                    <!-- DROPDOWN ARROW FOR COG
                    <img src="/images/global/header/dropdown_arrow_outline.png" class='pointer nav-cog-background' id='nav-cog-arrow'/>
                    -->
                </div>
                <div class='dropdown-back-outer' id='nav-dropdown-outer-cog'>
                        <div class='dropdown-back-inner' id='nav-dropdown-inner-cog'>
                             <a href="/users/<?php echo $this->user->userID;?>" class='header-dropdown-option-cog animate-opacity'>
                                 <div class='box-img-container-tiny left'><img src='<?php echo $this->user->getProfilePic('tiny');?>' class='cog-dropdown-account-pic box-img-tiny'/></div>
                                 <p class='white cog-dropdown-account-text cog-dropdown-account-text'><?php echo $this->user->shortName;?></p>
                             </a>
                             <a href="/users/<?php echo $this->user->userID;?>/inbox" class='header-dropdown-option-cog animate-opacity white'>
                                 Inbox (<?php echo $this->countNewMessages;?>)
                             </a>
                             <a href="/users/<?php echo $this->user->userID;?>/settings" class='header-dropdown-option-cog animate-opacity white' id='cog-dropdown-settings'>
                                 Account Settings
                             </a>
                             <a href="/login/logout" class='header-dropdown-option-cog animate-opacity white'>
                                 Logout
                             </a>
                        </div>
                 </div>
             </div>
             
             <div class='nav-back-short' id='nav-back-notification'>
             	<div class='green-back nav-notification-indicator-container'>
                	<p class='white centered arial nav-notification-indicator'><?php echo $this->user->notifications->countUnread();?></p>
                </div>
             </div>
             <div id='nav-back-notification-reverse'>
             </div>
        </div>
        
        <div class='header-nav-container-location'>
        	<p class='darker arial header-nav-location-text'>
            	You are in: &nbsp;
            </p>
            <p class='lighter arial header-nav-location-text location pointer' id='header-city'><?php echo ucwords($this->user->getCity()->city) . ', ' . strtoupper($this->user->getCity()->state);?></p>
        </div>
        