<div class='header-bar' id='header-bar-short'>
</div>
<div class='dropshadow-bottom' id='header-bar-location'>
</div>
<div class='dropshadow white-back' id='notifications-container'>
<?php
	foreach ($this->user->notifications->unread as $notification) {
		echo "<div href='" . $notification->getFormattedUrl() . "' class='notification-container light-green-back pointer'>" 
			 . "<div class='notification-text-picture-container'>"
				 . "<img src='" . $notification->getPicture() . "' class='notification-picture' />"
				 . "<span class='notification-text'>" . $notification->getFormattedText() . "</span>"
			 . "</div>"
			 . "<span class='notification-time-subscript light'>" . $notification->getTimeFromNow() . "</span>"
			 . "</div>";
		
	}
	foreach ($this->user->notifications->read as $notification) {
		echo "<div href='" . $notification->getFormattedUrl() . "' class='notification-container pointer'>" 
			 . "<div class='notification-text-picture-container'>"
				 . "<img src='" . $notification->getPicture() . "' class='notification-picture' />"
				 . "<span class='notification-text'>" . $notification->getFormattedText() . "</span>"
			 . "</div>"
			 . "<span class='notification-time-subscript light'>" . $notification->getTimeFromNow() . "</span>"
			 . "</div>";
	}
?>
</div>

<div id='city-change-container' class='medium-background dropshadow'>
	<?php echo $this->changeCityForm->changeCity;?>
    <p class='lighter smaller-text center width-100 clear' id='city-change-or'>or</p>
    <?php echo $this->changeCityForm->changeZipcode;?>
    <p id='city-change-reset' class='underline lighter smaller-text pointer '>reset to home</p>
    <div id='city-change-results-container'>
    </div>
</div>

<div id='header-search-results-container'>
</div>

    <div class='centered-body body-wrapper'>
    	<div class='header-nav-container-short'>
        	<a href='/'><img src='/images/global/logo/small.png' id='logo-small'/> </a>
            
            <a href='/'><img src='/images/global/header/home_icon.png' id='header-home-icon' /></a>
            
            <div class='nav-back-short nav-dropdown' id='nav-back-find'>
                <a href='/find' class='nav nav-out-short lightest' id='nav-find'>
                <p class='nav-dropdown-text'>FIND</p>
                
                </a>
                
                <div class='dropdown-back-outer' id='nav-dropdown-outer-find'>
                    <div class='dropdown-back-inner' id='nav-dropdown-inner-find'>
                        <?php 
							$find = array('games','teams','players','tournaments','groups');
							foreach ($find as $section) {
								echo $this->partial('partials/global/headerDropdownOption.phtml', array('controller' => 'find','section' => $section));
							}
						?>
                    </div>
                </div>
            </div>
            
            <div class='nav-back-short nav-dropdown' id='nav-back-create'>
                <a href='/create' class='nav nav-out-short lightest' id='nav-create'>
                	<p class='nav-dropdown-text'>CREATE</p>
                     
                </a>
                                                
                <div class='dropdown-back-outer' id='nav-dropdown-outer-create'>
                    <div class='dropdown-back-inner' id='nav-dropdown-inner-create'>
                         <?php 
							$create = array('game','team','group');
							foreach ($create as $section) {
								echo $this->partial('partials/global/headerDropdownOption.phtml', array('controller' => 'create','section' => $section));
							}
						?>
                    </div>
                </div>
            </div>
            
            <?php
				echo $this->headerSearchForm;
			?>
            
            <div class='nav-click-dropdown nav-back-short' id='nav-back-cog'>
            	<div id='nav-cog'>
                    <img src="/images/global/header/cog.png" class='pointer nav-cog-background'/>
                    <!-- DROPDOWN ARROW FOR COG
                    <img src="/images/global/header/dropdown_arrow_outline.png" class='pointer nav-cog-background' id='nav-cog-arrow'/>
                    -->
                </div>
                <div class='dropdown-back-outer' id='nav-dropdown-outer-cog'>
                        <div class='dropdown-back-inner' id='nav-dropdown-inner-cog'>
                             <a href="/users/<?php echo $this->user->userID;?>" class='header-dropdown-option-cog animate-opacity'>
                                 <div class='box-img-container-tiny left'><img src='<?php echo $this->user->getProfilePic('tiny');?>' class='cog-dropdown-account-pic box-img-tiny'/></div>
                                 <p class='white cog-dropdown-account-text cog-dropdown-account-text animate-opacity'><?php echo $this->user->shortName;?></p>
                             </a>
                             <a href="/users/<?php echo $this->user->userID;?>/inbox" class='header-dropdown-option-cog animate-opacity white'>
                                 Inbox (<?php echo $this->countNewMessages;?>)
                             </a>
                             <a href="/users/<?php echo $this->user->userID;?>/settings" class='header-dropdown-option-cog animate-opacity white' id='cog-dropdown-settings'>
                                 Account Settings
                             </a>
                             <a href="/login/logout" class='header-dropdown-option-cog animate-opacity white'>
                                 Logout
                             </a>
                        </div>
                 </div>
             </div>
             
             <div class='nav-back-short' id='nav-back-notification'>
             	<div class='green-back' id='nav-notification-indicator-container'>
                	<p class='white centered arial' id='nav-notification-indicator'><?php echo $this->user->notifications->countUnread();?></p>
                </div>
             </div>
             <div id='nav-back-notification-reverse'>
             </div>
        </div>
        
        <div class='header-nav-container-location'>
        	<p class='darker arial header-nav-location-text pointer'>
            	You are in: &nbsp;
            </p>
            <p class='lighter arial header-nav-location-text location pointer' id='header-city'><?php echo ucwords($this->user->getCity()->city) . ', ' . strtoupper($this->user->getCity()->state);?></p>
        </div>