<div class='header-bar dropshadow' id='header-bar-tall'>
</div>
	
    <div class='centered-body body-wrapper'>
    	<a href='<?php echo $this->url(array('controller' => 'index',
                                              'action'	  => 'index'));?>'><img src="/images/global/logo/large2.png" id='logo-large' /></a>
    	<div class='header-nav-container'>
            <div class='nav-back' id='nav-back-how'>
                <a href='<?php echo $this->url(array('controller' => 'how',
                                                 'action'	  => 'index'));?>' class='nav nav-out lightest' id='nav-how'>HOW DOES IT WORK</a>
            </div>
            <div class='nav-back' id='nav-back-signup'>
                <a href='<?php echo $this->url(array('controller' => 'signup',
                                                 'action'	  => 'index'));?>' class='nav nav-out lightest' id='nav-signup'>SIGNUP FREE</a>
            </div>
            <div class='nav-back nav-dropdown' id='nav-back-login'>
                <a href='<?php echo $this->url(array('controller' => 'login',
                                                     'action'	  => 'index'));?>' class='nav nav-out lightest' id='nav-login'>
                    <p class='nav-dropdown-text'>LOGIN</p>
                    <img src='/images/global/dropdown/dropdown_arrow.png' class='header-dropdown-arrow' />
                </a>
                <div class='dropdown-back-outer' id='nav-dropdown-outer-login'>
                    <div class='dropdown-back-inner' id='nav-dropdown-inner-login'>
                        <?php echo $this->dropdownLoginForm;?>
                    </div>
                </div>
            </div>
        </div>
    

