<?php
/* 
* controller => signup
* action => index
*/
$this->headTitle('Signup');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/signup.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/plugins/jcrop.min.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/signup.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/plugins/smartslider.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/plugins/jcrop.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/plugins/jform.js');
$this->headScript()->prependFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyAhxSMQ-WQux2nzTW4dBoKmpfGHVQOk7r8&sensor=false');
?>

<form action="<?php echo $this->form->getAction() ?>"
      enctype="<?php echo $this->form->getEnctype() ?>"
      method="<?php echo $this->form->getMethod() ?>"
      id="<?php echo $this->form->getId() ?>"
      class="<?php echo $this->form->getAttrib('class') ?>" >
<?php

$this->placeholder('absolute')->captureStart();
?>
<p class='medium' id='noAddress-text'>
	The system will not be as accurate while matching you.
</p>

<?php
echo $this->partial('partials/global/alertBack.phtml');
echo $this->alert()->start('signup-import','Upload and crop your image.');
?>
<img class='signup-import-alert-img' id='signup-import-alert-img' src='/images/global/profile/xl/default.jpg' />
<div class='signup-import-alert-text-container'>
	<p class='medium clear' id='signup-import-alert-guidelines-header'>Profile pictures should be:</p>
	<ul class='green heavy' id='signup-import-alert-guidelines'>
    	
    	<li>easily recognizable</li>
        <li>a clear shot of your face</li>
    </ul>
	<div class='button import-button' id='signup-import-alert-button'>
    	Choose Photo
        <form action="/ajax/upload-temp-picture" enctype="multipart/form-data" name='file_upload' id='upload-profile-pic'>
    		<input type='file' name='profilePic' id='profilePic' accept="image/*"/>
        </form>
    </div>
    <div id='signup-alert-rotate-container' class='clear width-100 clear'>
        <img src='/images/global/img_upload/rotate_left.png' class='clear signup-alert-rotate pointer hidden' id='signup-alert-rotate-left' tooltip='Rotate image left'/>
        <img src='/images/global/img_upload/rotate_right.png' class='right signup-alert-rotate pointer hidden' id='signup-alert-rotate-right' tooltip='Rotate image right'/>
    </div>
	<p class='medium' id='signup-import-alert-warning'>
    	If players cannot recognize you by your picture, you <span class='heavy medium'>will not receive any ratings.</span>
    </p>
    <div class='width-100 clear' id='signup-import-alert-accept-container'>
    	<p class='red smaller-text right pointer hidden' id='signup-import-alert-cancel'>cancel</p>
        <div class='button green-button larger-text right hidden' id='signup-import-alert-accept'>
            Accept
        </div>
        
    </div>
    
    <div id='signup-import-loading' class='left'>
    	<div class='left' id='loading-bar'></div>
    </div>
    
    <!--<img src='/images/global/loading.gif' id='signup-import-loading' />-->
   	
</div>
    
    	

<?php
echo $this->alert()->end();
$this->placeholder('absolute')->captureEnd();

if (!empty($this->errors)) {
	// There were errors
	echo "<div class='red-alert-box white'>";
	echo "Please fix the following:";
	echo "<ul>";
	foreach ($this->errors as $key => $val) {
		echo "<li style='float:left;clear:both'>" . $val . "</li>";
	}
	echo "</ul>";
	echo "</div>";
}
?>
<p class='larger-text green heavy clear width-100 center'>Sportfast is free and easy.</p>
<?php

$totalSteps = 4;
$currentStep = 1;

/* SIGNUP SECTION 1: ACCOUNT INFO */
echo $this->partial('partials/signup/stepContainer.phtml',array('title'		  =>'Account Info',
																'currentStep' =>$currentStep,
																'totalSteps'  =>$totalSteps));
$currentStep++;
echo $this->form->firstName;
echo $this->form->lastName;
echo $this->form->sex;
?>
<div id='signup-sex-container' class='dropshadow'>
    <div src='/images/signup/sex/male_sprite.png' class='signup-sex-img pointer' id='signup-sex-male' tooltip='Male'></div>
    <div class='signup-sex-img pointer' id='signup-sex-female' tooltip='Female'></div>
</div>
<?php
echo "<div class='clear'></div>";
echo $this->form->dobMonth;
echo "<span class='signup-dob-slash'>/</span>";
echo $this->form->dobDay;
echo "<span class='signup-dob-slash'>/</span>";
echo $this->form->dobYear;
echo $this->form->age; // hidden
echo $this->form->heightFeet;
echo "<span class='signup-dob-slash signup-dimension-indicator' id='heightFeet-indicator'>'</span>";
echo $this->form->heightInches;
echo $this->form->height;
echo "<span class='signup-dob-slash signup-dimension-indicator' id='heightInches-indicator'>\"</span>";


echo "<div class='clear signup-clear-large'></div>";
echo $this->form->email;
echo "<div class='clear'></div>";
echo $this->form->signupPassword;
// use same setup as signup password, but change ID bits
echo $this->form->signupPassword->setLabel('Re-enter Password')->setAttribs(array('id'=>'signupReenterPassword','name'=>'signupReenterPassword'));
?>
<div id='signup-password-reqs' class='medium hidden'>Password must be: <ul><li>8-12 characters long</li></ul></div>
</div>

<?php
echo "<div class='clear signup-clear-large'></div>";
?>
<p class='green heavy smaller-text' id='signup-account-address-warning'>
	This address will be used to find games, players, and teams closest to you.  It will never be displayed and will only be used to help find optimal matches.
</p>

<p id='signup-account-zipcode-city' class='medium smaller-text'></p>
<?php
echo $this->form->streetAddress;
echo $this->form->zipcode;
echo $this->form->userLocation;
?>

<div class='clear'></div>


<?php
echo $this->form->noAddress;
?>


<?php
/* SIGNUP SECTION 2: SPORTS */
echo $this->partial('partials/signup/stepContainer.phtml',array('title'		  =>'Sports',
																'currentStep' =>$currentStep,
																'totalSteps'  =>$totalSteps));
$currentStep++;

?>
<p class='medium center' id='signup-sports-what'>What sports are you interested in playing?</p>
<div id='signup-sports-icons-container'>
<?php
	$sports = $this->sports;

foreach ($sports as $sport => $values) {
	echo $this->partial('partials/signup/sportIcon.phtml',array('sport' =>$sport));
}

?>
</div>


	<?php
	// create sportForms							
    echo $this->signupsportform()->loop($sports);

	?>




</div>
<?php
/* STEP 3 IMPORT PHOTO */
echo $this->partial('partials/signup/stepContainer.phtml',array('title'		  =>'Import Picture',
																'currentStep' =>$currentStep,
																'totalSteps'  =>$totalSteps));
															
$currentStep++;


?>
<p class='clear medium signup-import-main-current-text'> Current picture:</p>
<div class='signup-import-main-img-container'>
    <img src='/images/users/profile/pic/large/default.jpg' class='signup-import-main-img' id='signup-import-main-img'/>
</div>
<div class='signup-import-main-text-container'>
	<p class='center green larger-text'>
    	You may signup without a picture, but players without one <span class='green-bold'>won't receive ratings.</span>
    </p>
    <div id='signup-import-main-upload-button-container'>
        <div class='button larger-text' id='signup-import-main-upload-button'>
            Upload Picture
        </div>
    </div>
    <p class='pointer width-100 center dark clear why-profile'>
    	Why do I need a profile picture?
    </p>
    <p class='center width-100 smaller-text light clear larger-margin-top'>
    	You can add/edit your profile picture under Account Settings later.
    </p>
    
</div>
<?php
// Hidden inputs for picture info
echo $this->form->fileName;
echo $this->form->fileWidth;
echo $this->form->fileHeight;
echo $this->form->fileX;
echo $this->form->fileY;
?>    	

</div>
<?php

echo $this->partial('partials/signup/stepContainer.phtml',array('title'		  =>'Agree',
																'currentStep' =>$currentStep,
																'totalSteps'  =>$totalSteps));
$currentStep++;

?>
<p class='signup-agree-header center'>
We are not a dating site.  We are not a site for funny videos.  We play sports.  As athletes, we adhere to a general code of conduct.  That conduct is laid out in our Pledge:
</p>
<div class='signup-agree-pledges-container'>
	<?php
		echo $this->partial('partials/signup/agreePledge.phtml', array('pledge'      => 'My word is golden.',
																	   'description' => "If I say I will be there, then that's where I'll be."));
																	   
		echo $this->partial('partials/signup/agreePledge.phtml', array('pledge'      => 'No man left behind.',
																	   'description' => "Everyone gets to play.  No exceptions."));

		echo $this->partial('partials/signup/agreePledge.phtml', array('pledge'      => 'No whining.  Kids whine.',
																	   'description' => "We are here to play sports."));

	
	?>
</div>
<?php
echo $this->form->agree;
?>
</div>

<div class='button green-button header' id='signup-finish'>
	FINISH
</div>

</form>


<?php
/* NARROW COLUMN */
$this->placeholder('narrowColumn')->captureStart();
?>
<div class='signup-import-main-img-container signup-narrow-column-img-container'>
    <img src='/images/users/profile/pic/large/default.jpg' class='narrow-column-picture' />
</div>

<?php
// Account Info
echo $this->narrowcolumnsection()->start(array('title' => 'Account Info'));
											   ?>
<div id='account-info-name' class='capitalize narrow-column-value'>
    <span id='account-info-first-name' class='narrow-column-value bold'></span>
    <span id='account-info-last-name' class='narrow-column-value bold no-clear'></span>
</div>
<div id='account-info-sex' class='narrow-column-fade narrow-column-value'>
</div>
<div id='account-info-age' class='narrow-column-fade narrow-column-value'>
</div>
<div id='account-info-dimensions' class='narrow-column-value'>
	<span id='account-info-height' class='narrow-column-fade'></span>
    <!--<span id='account-info-weight' class='narrow-column-fade no-clear'></span>-->
</div>
<div id='account-info-location' class='narrow-column-value'>
</div>
       
<?php 
// Sports section
echo $this->narrowcolumnsection()->end(); 
echo $this->narrowcolumnsection()->start(array('title' => 'Sports'));

foreach ($sports as $key => $val) {
	echo "<img src='/images/signup/sports/icons/medium/" . $key . ".png' class='signup-sport-icon-narrow-column' id='signup-narrow-column-sport-" . $key . "'/>";
}
										  
?>

<?php
echo $this->narrowcolumnsection()->end(); 
$this->placeholder('narrowColumn')->captureEnd();