<?php
/* 
* controller => signup
* action => validate
*/
$this->headTitle('Verify Email');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/signup.css');
?>

<div class='clear white-back rounded-corners dropshadow' id='signup-validate-container'>
	<?php
	
	if ($this->success) {
		$email = explode('@', $this->username);
		
		echo "<p class='clear largest-text green heavy width-100 center'>Almost done!</p>";
		echo "<p class='medium clear width-100 center larger-margin-top'>An email verification has been sent to: <br><a href='http://www." . $email[1] . "'  class='inherit underline darkest heavy largest-text' target='_blank'>" . $this->username . "</a></p>
				<p class='clear darkest width-100 heavy center margin-top'>Please follow the link in this email to complete your signup.</p>
				<p class='clear medium width-100 center larger-margin-top'>(if you can't find it, check your spam folder)</p>";
	} else {
		echo "<p class='clear largest-text red heavy width-100 center'>An Error Occurred</p>";
		echo "<p class='darkest clear width-100 center larger-text larger-margin-top'>An email could not be sent to " . $this->username . ".
				<br><br>We are aware of this failure and will contact you shortly.  Sorry for the inconvenience!</p>";
	}
	?>
</div>