<?php
/* 
* controller => login
* action => index
*/
$this->headTitle('Login');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/login.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/login.js');
?>

<?php

$this->placeholder('absolute')->captureStart();
	echo $this->partial('partials/global/alertBack.phtml');
	
if ($this->email) {
	// Forgot password invoked
	echo $this->alert()->start('forgot');
		
		echo "<p class='darkest width-100 center'>An email has been sent to <br><span class='larger-text darkest heavy'>" . $this->email . "</span>.";
		
	echo $this->alert()->end();
	
	
}

if ($this->already) {
	// Forgot password invoked
	
	echo $this->alert()->start('already');
		
		echo "<p class='darkest width-100 center'>" . $this->already . " already has an account associated with it.</p>";
		
	echo $this->alert()->end();
	
	
}

$this->placeholder('absolute')->captureEnd();
?>

<div id='login-form-container'>
	<p class='bold darkest' id='login-header'>
    	LOGIN TO YOUR ACCOUNT
    </p>
    <img src='/images/login/runner.png' id='login-header-img' />
    <div id="login-form-back" class='white-back dropshadow'>
        <?php echo $this->form;?>
        <a href='/signup' class='clear smaller-text medium' style='margin-left: 2.2em'>No Account? Signup is free!</a>
    </div>
</div>