<!--CLOSE CENTERED-BODY DIV-->
<div class='push'></div>
</div>
<div class='footer'>
    <div class='centered-body'>
        <div class="ads">
            <div class="ad-center leaderboard">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- sportfast_footer_728x90 -->
                <ins class="adsbygoogle"
                     style="display:inline-block;width:728px;height:90px"
                     data-ad-client="ca-pub-3057861132108543"
                     data-ad-slot="9199664117"></ins>
                <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
        </div>
    	<div class='footer-section' id='footer-section1'>
        	<p class='footer-section-title light'>
            	Help &amp; Info
            </p>
            <?php 
			$links = array('FAQ' 		 => array('controller' => 'about',
											 	  'action'	   => 'faq'),
						   'Sport Rules' => array('controller' => 'sports',
											 	  'action'	   => 'index'));
			echo $this->footer($links); 
			?>
        </div>
        <div class='footer-section' id='footer-section2'>
        	<p class='footer-section-title light'>
            	What is Sportfast?
            </p>
			<p class='footer-section-links medium'>
            	Sportfast is your home for everything recreational. We provide a place 
                for local athletes to find and organize everything from 
                pickup games to league teams.
            </p>
        </div> 
        <div class='footer-section' id='footer-section3'>
        	<p class='footer-section-title light'>
            	The Company
            </p>
            <?php 
			$links = array('About Us' 		 		=> array('controller' => 'about',
											 	  			 'action'	  => 'index'),
						   'Contact' 				=> array('controller' => 'contact',
											 	  			 'action'	  => 'index'),
						   'Jobs'				 	=> array('controller' => 'about',
											 	  			 'action'	  => 'jobs'),
						   'Privacy Policy' 		=> array('controller' => 'about',
											 	  			 'action'	  => 'privacy'),
						   'Terms &amp; Conditions' => array('controller' => 'about',
											 	  			 'action'	  => 'terms'));
			echo $this->footer($links); 
			?>
        </div>         	
    </div>
</div>