<?php
/** 
 * controller => about
 * action => pickup
 */
$this->headTitle('About Leagues');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/about.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/about.js');
?>

<header class='jumbo-text darkest heavy clear'>
	About Leagues
</header>

<div class='clear width-100 margin-top'>
<img src='/images/about/leagues/leagues.jpg' class='larger-indent' align='right'/>
    <p class='darkest larger-text'>
		Leagues allow players to compete on a level above pickup games.  <span class='heavy'> Leagues consist of several teams that play against
        one another in reffed games throughout the course of a season and then into playoffs.</span>  It is similar to high school or college sports, 
        except the players can be anyone from any skill level.  Leagues are organized by outside parties (typically the city), and so there are almost always fees associated
        with registering in a league.
        <br>
        <br>
    </p>    
    
</div>

<p class='clear jumbo-text darkest heavy'>
	How to find a team
</p>
<div class='clear'>
    <p class='darkest larger-text'>
    	Typically, teams need to be put together by the players themselves.  One player will act as "team captain" and ask their friends and people they know 
        to play on their team.  That team captain will then need to contact the league, get the necessary forms, fill them out, go to the league's office, 
        pay the registration fee, and wait for schedules to come out.  The captain will then be responsible for organizing their team and occassionally 
        corresponding with the league organizer.
    </p>
    <br>
    <br>
</div>

<div class='clear'>
    <p class='darkest larger-text'>
    	 Normally, this means that if you don't personally know someone who already has a team, you won't be able to play in a league.  
         Here at Sportup, we think that's so primitive.  There are plenty of players out there who want to play in a league.  Why can't we match them up and 
         put together some quality league teams?  The answer is: we can.  If you show interest in league play for a certain sport, our system will find other
         suitable players for your team and, when there are enough players, will create the team for you.  For now, you are still needed to register your team
         with the league as well as input your schedule on your team's Sportup page, but soon we will implement a new system to remove those steps from the process.
    </p>
    <br>
    <br>
</div>

<p class='clear jumbo-text darkest heavy'>
	How to find a league
</p>
<div class='clear'>
    <p class='darkest larger-text'>
    	Leagues are common, but are not available everywhere.  The simplest way is to google "[sport] leagues in [your city]", and find the top couple results.
        Most leagues worth their weight will have a website with more information about the league.  It is important to recognize what skill level you want to play in,
        as most leagues have several options ranging from A (best) to D (beginner).  If you are unsure what skill level a league is, contact the league organizer through
        the website.  They are very accomodating and honestly *want* you to join their league.  We our expanding our database of leagues, but as we are still in beta, they
        are not accessible.
    </p>
    <br>
    <br>
</div>


<p class='clear jumbo-text darkest heavy'>
	How much does it cost
</p>
<div class='clear'>
    <p class='darkest larger-text'>
    	League teams can cost anywhere from $100 to $900 per team depending on how long they are as well as what services they provide.  If the league
        provides detailed statistics on your games (uncommon) then it is going to be in the $900 range.  Most 3 month leagues (standard) will cost about $600 per team.
        These are just rough estimates based on what we have seen.  To know the exact cost, contact the league or look on their website for information.
    </p>
    <br>
    <br>
</div>
