<?php
echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/global.css') . PHP_EOL;
?>
<style>
body {
	background:#F3F3F3;
}
</style>
<header class='margin-top indent larger-text heavy clear darkest' >
	Why do I need a profile picture?
</header>
<p class='clear darkest larger-margin-top' style='padding: 0 .75em;text-align:justify;'>
	The internet can be an intimidating place, especially when it comes to meeting strangers in person.  We don't want that.  
    <span class='green heavy'>We want every user to feel comfortable by knowing exactly who they will be playing with.</span>  A big part of that comfort comes from a picture.
    Wouldn't you feel more comfortable seeing a nice, smiley picture rather than a big question mark?  Your picture will also allow other users to rate your performance.
    And so, with this in mind, we require every user to have a profile picture in order to receive ratings from other players based on skill, sportsmanship and your best skill (e.g. passing, defense, etc).
</p>