<?php
echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/global.css') . PHP_EOL;
?>
<style>
body {
	background:#F3F3F3;
}

#ratings-img {
	margin-left:8.5em;
}

p {
	padding: 0 .75em;
}
</style>
<header class='margin-top indent larger-text heavy clear darkest' >
	What are ratings?
</header>

<p class='clear darkest indent margin-top' >
	After a pickup game, users will have the option to anonymously rate a randomly-selected user they played with.  Users rate you based on 3 categories: <span class='green heavy'>skill<span class='darkest'>,</span> sportsmanship<span class='darkest'>, and</span> attendance</span>.
    In addition, users can highlight a skill that they thought you excel at (such as passing, defense, etc).  These ratings can be tracked on your profile page so you can see how you perform over time.  
    If you have an impressive game, your fellow players will most likely reward you with impressive ratings.  This is your chance to see how other players view your playing style and will help you improve over time.
    
</p>
