<?php
$this->headTitle('Terms of Service');
?>
<style>
h1 {
	font-family: 'Futura-Heavy', Arial;
	font-size: 1.5em;
	
}

</style>

<header class='jumbo-text darkest heavy'>
	Terms of Service
</header>
<br>
Before using any of Sportfast.com's services, you are required to read, understand and agree to these terms. You may only create an account after reading and accepting these terms.

<br><br>
<h1>1. Acceptance of Terms</h1>
<br>
The web pages available at Sportfast.com and all linked pages ("Site"), are owned and operated by Sportfast, and is accessed by you under the Terms of Use described below ("Terms").

Please read these terms carefully before using the services. By accessing the Site, viewing any content or using any services available on the Site (as each is defined below) you are agreeing to be bound by these terms, which together with 
our Privacy policy, governs our relationship with you in relation to the Site. If you disagree with any part of the terms then you may not access the Site.

<br><br>
<h1>2. Description of Service</h1>
<br>
The Site provides our users with a variety of resources to facilitate organizing, creating, finding, and managing of sports-related games and teams (a "Game" or "Team").
<br><br>
You agree to comply with all applicable domestic and international laws, statutes, ordinances and regulations regarding your use of our Site, including without limitation your participation in or involvement with any Game 
or Team (as defined in Section 6.1) and your submission of acceptable Public Information (as defined in Section 5 ("Your Information")). You also agree to comply with all applicable laws, statutes, ordinances and regulations 
regarding the transmission of technical data exported from the United States or the country in which you reside.

<br><br>
<h1>3. Membership</h1>
<br>3.1 <b>Eligibility.</b> Our Site is available to all individuals who are at least 18 years of age. Our Site is not available to any temporarily or indefinitely suspended Sportfast users. By registering to use our Site, 
you represent and warrant that you are at least 18 years of age. Additional eligibility requirements for a particular Game or Team may be set by the organizer or co-organizer of a 
Game (an "Organizer") or captain or co-captain ("Captain") of a Team.

<br><br>We have the right, in our sole discretion, to suspend or terminate your use of our Site and refuse any and all current or future use of all or any portion of our Site.

<br><br>3.2 <b>Password and Security.</b> When you complete our registration process you will create a password that will enable you to access our Site. You agree to maintain the confidentiality of your password, and are fully 
responsible for all liability and damages resulting from your failure to maintain that confidentiality and all activities that occur through the use of your password. You agree to immediately notify us of any unauthorized use of 
your password or any other breach of security. You agree that Sportfast cannot and will not be liable for any loss or damage arising from your failure to comply with this Section 3.2.

<br><br>
<h1>4. Fees and Payments</h1>
<br>4.1 <b>General.</b> Access to our websites and use of selected features of our Site is free. We may charge fees for various premium features and services that we offer, and we will notify you of those charges at the time that 
we offer you the premium features or services for a fee. We may, in our sole discretion, and by notifying you on our website, change this policy and begin charging for access to our website and other features and services, and we may, 
in our sole discretion, add, remove or change the features and services we offer or the fees (including the amount or the type of fees) we charge at any time. If we introduce a new service or charge a new fee, we will establish and notify 
you of the fees for that service at the launch of the service or start of charging a new fee. If we notify you of new fees or change the fees for an existing service, you agree to pay all fees and charges specified and all applicable taxes 
for your continued use of the applicable service. We are not responsible for any charges or expenses you incur resulting from being billed by us in accordance with these Terms of Service (e.g., overdrawn accounts, exceeding account limits, etc.).

<br><br>4.2 <b>Fees Assessed by Teams.</b> Some Captains may request or require fees for participation in a Team.  These Team fees are at the discretion of each Captain, who decides whether such fees are required, the amount frequency, payment options, refund policies, and how such fees are spent.
To the extent that you use Amazon Payments, PayPal or another payment mechanism (e.g., check or cash), to pay fees assessed by a Captain, you acknowledge that Sportfast does not control the transaction, and that you bear all risk in connection with the transaction. Refunds of any payment 
you make to any Captain are subject to that Captain's policies and applicable law. If you believe any payment to an Captain is in error, you must contact the Captain to seek resolution. You should use common sense and be careful in 
deciding whether to make a payment to a Captain. Captains have full discretion whether and how to spend money in connection with their Teams. We cannot ensure that a Captain is legitimate and truthful, that he or she will use payments as promised, 
or that you will be happy with how your payment is spent. Your correspondence or business dealings with, or participation in promotions of Sportfast Teams, including payment and related services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and the applicable 
Captain.

<br><br>4.3 <b>Consent to Disclosure.</b> You acknowledge and agree that Sportfast may disclose Your Information (as defined in Section 5) if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to:(a) comply with a current judicial 
proceeding, a court order or legal process served on us or our website, (b) enforce this Agreement, (c) respond to claims that Your Information violates the rights of third parties; (d) protect the rights, property or personal safety of Sportfast, its employees, users and the public; or (e) 
enable the transfer or sale to another entity of all or substantially all of our stock or assets in the line of business to which this Agreement relates, or upon any other corporate reorganization, subject to the promises made in this Agreement. We also may disclose any information about you 
to law enforcement or other government officials as we, in our sole discretion, believe necessary or appropriate, in connection with an investigation of fraud, intellectual property infringements, or other activity that is illegal or that we believe may expose us or you to legal liability.

<br><br>
<h1>5. Your Information</h1>
<br>5.1 <b>Definition.</b> "Your Information" is defined as any information post or other material you provide (directly or indirectly), including through the registration process for a Game or Team, or through registration for membership on the Site, or through the use of 
our Site, in any public message board or through email. You are solely responsible for Your Information, and we act as a passive conduit for your online distribution and publication of your Public Information (as defined below).

Any of Your Information that, through the use of our Site or otherwise, you submit or make available for inclusion on publicly accessible areas of our website is referred to as "Public Information" (your name, age, height, weight, sex, city of residence, profile picture, ratings, and participation in Games or Teams are considered Public Information); any other portion of Your Information shall be referred to 
as "Private Information." "Publicly accessible" areas of our website are those areas that are available either to some or all of our members (i.e., not restricted to your viewing only) or to the general public.

You should understand that your Public Information may be accessible by and made public through syndication programs (including data feed tools) and by search engines, metasearch tools, crawlers, metacrawlers and other similar programs.

<br><br>5.2 <b>Restrictions.</b> In consideration of your use of our Site, you agree that Your Information:
<ol type='a'>
<li> shall not be fraudulent;</li>
<li> shall not infringe any third party's copyright, patent, trademark, trade secret or other proprietary rights or rights of publicity or privacy;</li>
<li> shall not violate any law, statute, ordinance or regulation;</li>
<li> shall not be defamatory, trade libelous, unlawfully threatening or unlawfully harassing;</li>
<li> shall not be obscene or contain, pornography, child pornography, or photographs of unclothed person(s);</li>
<li> shall not contain any viruses, Trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information;</li>
<li> shall not create liability for us or cause us to lose (in whole or in part) the services of our ISPs or other suppliers;</li>
<li> shall not link directly or indirectly to any materials to which you do not have a right to link to or include.</li>
</ol>
<br> In addition, you agree that you will provide us with your valid, current email address, both at the time of your registration with us and from time to time as your email address changes.

<br><br>5.3 <b>License.</b> We do not claim ownership of Your Information. We will use Your Information only in accordance with our privacy policy. However, to enable us to use your Public Information and to ensure we do not violate any rights you may have in your Public Information, 
you grant Sportfast a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sublicensable (through multiple tiers) right to exercise, commercialize and exploit the copyright, publicity, and database rights (but no other rights) you have in your Public Information, in any media 
now known or not currently known, with respect to your Public Information.

<br><br>5.4 <b>Restriction on Use of Your Information.</b> Except as otherwise provided in our privacy policy, we will not sell, rent or otherwise disclose any of your Personally Identifiable Information (as defined in our privacy policy) about you (including your email address) to any third party.

<br><br>
<h1>6. Use of Site</h1>
<br>6.1 <b>Control.</b> You, and not Sportfast, are entirely responsible for all of your Public Information that you upload, post, email, transmit or otherwise make available via our Site. We do not control your Public Information or the Public Information of or posted by other users and do not 
guarantee the accuracy, integrity or quality of Your Information or the Information of or posted by other users. Nor do we endorse any opinions expressed by you or other users. You understand that by using our Site, you may be exposed to information that is offensive, indecent or objectionable. 
We do not have any obligation to monitor, nor do we take responsibility for, Your Information, Public Information or information of or posted by other users. You agree that under no circumstances will Sportfast its directors, officers, shareholders, employees, consultants, agents, advisers, affiliates, 
subsidiaries or its third-party partners be liable in any way for any information, including, but not limited to, for any errors or omissions in Your Information or the Information of or posted by other users, or for any loss or damage of any kind incurred as a result of the use of Your Information or 
Information of or posted by other users posted, emailed, transmitted or otherwise made available in connection with our Site, or for any failure to correct or remove information.

<br><br>6.2 <b>API License.</b> Subject to the terms and conditions of this Agreement, Sportfast grants you a limited, non-exclusive, non-transferable, non-sublicensable license to use any application programming interface ("API") that Sportfast makes available via the Site for the sole purpose of integrating or 
making available Public Information on another web site. Sportfast reserves all rights not expressly granted under this Agreement.

<br><br>6.3 <b>Grounds for Removal, Sanction and/or Suspension.</b> Notwithstanding any other provision of this Agreement, the following types of actions are cause for immediate removal, repeal and/or suspension or termination of your account:
<ol type='a'>
<li>The use of our Site to (including, without limitation, eligibility requirements):</li>
	<ol type='i'>
    <li>harm or intimidate another person in any way, including restricting or inhibiting any other user from using our Site;</li>
    <li>impersonate any person or entity (including Sportfast, Sportfast staff and other members), or falsely state or otherwise misrepresent 
    	your affiliation with any person, through the use of similar email addresses, nicknames, or creation of false account(s) or any other method or device;</li>
    <li>disguise the origin of any Public Information that is transmitted to any third party;</li>
    <li>"stalk" or otherwise harass another;</li>
    <li>advertise merchandise, auctions, services or commercial websites, including offers to trade or charitable solicitations unrelated to the topic or spirit of the Sportfast Game or Team;</li>
    <li>resell Public Information or access to Public Information;</li>
    or <li>collect or store personal data about other users;</li>
    </ol>
<li>Posting any Public Information or other material:</li>
	<ol type='i'>
    <li>that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, intimidating, vulgar, obscene, profane, libelous, invasive of another's privacy (including the posting of private emails or contact 
    information about another individual), hateful, or racially, ethically or otherwise objectionable, including any Public Information or other material that may be considered hate speech;</li>
    <li>that is obscene, pornographic or adult in nature;</li>
    <li>that you do not have a right to make available under any law or under contractual or fiduciary relationships;</li>
    <li>that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party or rights of publicity or privacy;</li>
    <li>that is unsolicited or unauthorized advertising, promotional materials, or any other form of solicitation (including, but not limited to, "spam," "junk mail," and "chain letters");</li>
    <li>that is inappropriate, posted in bad faith, or contrary to the spirit of any Sportfast Game or Team;</li>
    or <li>that uses the Site primarily as a lead generator or listing service for another website;</li>
    </ol>
<li>Encouraging others to violate this Agreement;</li>
<li>Refusing to follow Sportfast staff instruction or direction;</li>
<li>Violation (intentional or unintentional) of this Agreement, or of any applicable local, state, national or international law, statute, ordinance or regulation;</li>
<li>Disclose the Private Information of any member of a Game or Team without the permission of that member; or</li>
<li>Transmit money to Sportfast or any Captain or Creator through financial accounts that are stolen, fraudulent or otherwise unauthorized.</li>
</ol>
<br>Also, your posting of other inappropriate actions, Public Information or other materials may also warrant removal and/or suspension from our website. Sportfast reserves the right to remove any post or other material without warning or further notice.

<br><br>While we prohibit such conduct and content, you understand and agree that you nonetheless may be exposed to such conduct or content and that you use the Site and attend Games at your own risk.

<br><br>For purposes of this Agreement, "posting" includes uploading, posting, emailing, transmitting or otherwise making available. Without limiting the foregoing, Sportfast and its designees shall have the right to remove any Public Information or other material that violates this Agreement or is otherwise objectionable.

<br><br>6.4 <b>Interference with Site.</b>
<br> You agree that you will not:
<ol type='a'>
	<li>upload, post, email, or otherwise transmit any computer routines, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
    <li>interfere with or disrupt our Site or networks connected to our website or through the use of our Site, or disobey any requirements, procedures, policies or regulations of networks connected to our website or through the use of our Site, or otherwise interfere with our Site in any way, including through the use 
    of JavaScript, active or other coding;</li>
    <li>take any action that imposes an unreasonable or disproportionately large load on our infrastructure; or</li>
    <li>copy, reproduce, alter, modify, or publicly display any information displayed on our website (except for Your Information), or create derivative works from our website (other than from Your Information), to the extent that such action(s) would constitute copyright infringement or otherwise violate the intellectual 
    property rights of Sportfast or any other third party, except with the prior written consent of Sportfast or the appropriate third party.</li>
</ol>

<br><br>6.5 <b>General Practices Regarding Use of Site.</b> You acknowledge and agree that we may establish general practices and limits concerning the use of our Site. You agree that we have no responsibility or liability for the storage or the deletion of, or the failure to store or delete, any of Your Information. 
You acknowledge that we reserve the right to log off and/or deactivate users who are inactive for an extended period of time. In addition, you acknowledge that we reserve the right to change these general practices and limits at any time, in our sole discretion, with or without notice.

<br><br>
<h1>7. Games</h1>
<br>7.1 <b>Sportfast Games.</b> Through our Site we provide tools that enable our users to arrange physical meetings (a "Game") at venues (a "Venue") that include, but are not limited to, public parks, gyms or schools. We do not supervise these 
Games and are not involved in any way with the actions of any individuals at these Games. As a result, we have no control over the identity or actions of the individuals who are present at these Games, and we request that our users exercise caution and good judgment when attending these Games.
Sportfast does not hold any responsibility or liability for the availability, accessibility or quality of a Venue, as well as the behavior or actions of its members while at a Venue.

<br><br>7.2 <b>General Release.</b> Because we do not supervise or control the Games or interactions among or between members of Teams and/or Games and other persons or companies, and because we are not involved in any way with physical transportation to or from Games or with the actions of any individuals 
at Games, and because we do not control Amazon.com, PayPal, credit card companies or other payment processing companies, and because we cannot guarantee the true identity, age, or nationality of Site users, and because we have very limited control, if any, over the quality, safety, morality, legality, 
truthfulness or accuracy of various aspects of the Site you agree that you bear all risk and you agree to release us (and our officers, directors, shareholders, agents, employees, affiliates, subsidiaries, and third party partners) and Captains and Organizers and their designees from claims, demands, and 
damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, now and in the future, arising out of or in any way connected with your use of the Site, your Third Party Transactions, our resolution of any disputes among users, and/or 
your transportation to or from, attendance at, or the actions of you or other persons at, a Game. You further waive any and all rights and benefits otherwise conferred by any statutory or non-statutory law of any jurisdiction that would purport to limit the scope of a release or waiver. You waive and 
relinquish all rights and benefits which you have or may have under Section 1542 of the Civil Code of the State of California or any similar provision of the statutory or non-statutory law of any other jurisdiction (including without limitation the states of Missouri, Delaware and Pennsylvania) to the 
full extent that you may lawfully waive all such rights and benefits.

<br><br>7.3 <b>Injury Release.</b> You acknowledge that the nature of sports-related Games may expose you to hazards or risks that may result in personal injury and you understand and appreciate the nature of such hazards and risks. In consideration of your participation in Games, you hereby accept all risk to 
your health and of your injury that may result from such participation and you hereby release Sportfast, Sportfast's members, the hosting Venue, employees and representatives from any and all liability to you, your personal representatives, estate, heirs, next of kin, and assigns for any and all claims and causes of action for loss of or 
damage to your property and for any and all illness or injury to your person, that may result from or occur during your participation in a Game, whether caused by negligence by Sportfast, Sportfast's members, the hosting Venue, employees, or representatives, or otherwise. You further agree to indemnify and hold harmless Sportfast, Sportfast's members, the hosting Venue, employees, 
and representatives from liability for the injury of any person(s) and damage to property that may result from your negligent or intentional act or omission while participating in a Game.

<br><br>
<h1>8. Communications from Sportfast and Members of Sportfast Community</h1>
<br>8.1 <b>Sportfast Communications.</b> You understand that certain communications, such as Sportfast service announcements and newsletters, as well as offers of sponsorship or promotion relevant and beneficial to you or your Game or Team, are part of our Site. By using our Site, you expressly agree to receive such communications from Sportfast. You may manage 
your subscriptions to Sportfast communications in the Account tab of the Account Settings page; however, some basic communications are a necessary part of our Site and may not be disabled.

<br><br>8.2 <b>Role of Organizer and Captain.</b> Please be aware that an Organizer or Captain is: (a) not Sportfast's representative or agent, and therefore an Organizer or Captain 
may not enter into contractual relations or obligations on Sportfast's behalf; (b) not entitled to enter into contractual relations or obligations on behalf of specific Team members unless expressly 
agreed by those Team members; and (c) acting independently, and therefore no contractual relationship or obligation arises between an Organizer/Captain or an individual Game/Team member unless otherwise agreed.

<br><br>
<h1>9. Privacy</h1>
Sportfast collects registration and other information about you through the Site. Our collection, use, and disclosure of this information is governed by the Sportfast Privacy Policy Statement available <a href='/about/privacy'>here</a>.

<br><br>
<h1>10. Links</h1>
We may provide, or third parties may provide, links to other websites or resources. Because we have no control over such websites or resources, you acknowledge and agree that we are not responsible for the availability of such websites or resources, and do not endorse 
and are not responsible or liable for any content, advertising, products, or other materials on or available from such websites or resources. You also acknowledge and agree that Sportfast shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged 
to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such websites or resource.

<br><br>
<h1>11. Indemnity</h1>
You agree to indemnify and hold us and our officers, directors, shareholders, agents, employees, consultants, affiliates, subsidiaries and third-party partners harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your breach 
of your representations and warranties or this Agreement or the documents it incorporates by reference, your use of our Site, Your Information, your violation of any law, statute, ordinance or regulation or the rights of a third party, your participation in a Sportfast Team or Sportfast Game, 
or your participation as an Organizer or Captain or Games(whether the claim or demand is due to or arising out of your transportation to or from, attendance at, or the actions of you or other users at Games). Without limiting the foregoing, you, as an Organizer or 
Captain, agree to indemnify and hold us and our officers, directors, shareholders, agents, employees, consultants, affiliates, subsidiaries and third-party partners harmless from any claim or demand, including reasonable attorneys' fees, made by any Sportfast Game or Sportfast Team member 
or third party due to or arising out of your actions as an Organizer or Captain, including your use of money paid to you by members of your Team.

<br><br>
<h1>12. Warranties and Liability</h1>
<br>12.1 <b>Disclaimer of Warranties.</b> Your use of our Site is at your sole risk. Our Site is provided to you "as is" and on an "as available" basis. We specifically disclaim all warranties and conditions of any kind, whether express, implied or statutory, including but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement. 
We disclaim any warranties regarding the security, reliability, timeliness, and performance of our Site. We disclaim any warranties for any information or advice obtained through our Site. We disclaim any warranties for services or goods received through or advertised on our Site or received through any links provided by our Site, as well as for any information or advice received 
through any links provided through our Site.

<br>In addition, no advice or information (oral or written) obtained by you from us shall create any warranty.

<br>You understand and agree that you download or otherwise obtain material or data through the use of our Site at your own discretion and risk and that you will be solely responsible for any damages to your computer system or loss of data that results from the download of such material or data.

<br><br>12.2 <b>Limitation of Liability.</b> You agree that in no event shall Sportfast be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses 
(even if Sportfast has been advised of the possibility of such damages), arising out of or in connection with our Site or this Agreement or the inability to use our Site (however arising, including negligence), arising out of or in connection with Third Party Transactions or arising 
out of or in connection with your use of our Site or transportation to or from Games, attendance at Games, participation in or exclusion from Games and the actions of you or others at Games. Our liability to you or any 
third parties in any circumstance is limited to the greater of (a) the amount of fees, if any, you pay to us in the twelve (12) months prior to the action giving rise to liability, and (b) $100.

<br><br>
<h1>13. Modifications</h1>
We reserve the right at any time or times to modify or discontinue, temporarily or permanently, all or any portion of our Site with or without notice. You agree that we shall not be liable to you or to any third party for any modification, suspension or termination of our Site.

<br><br>
<h1>14. Termination; Breach</h1>
You agree that we, in our sole discretion, may issue a warning, temporarily suspend, indefinitely suspend, remove content or information you have posted, or terminate your account your status as a particular Game or Team member or Organizer or Captain, 
or your ability to use all or any portion of our Site (including any APIs), for any reason, including, without limitation, (a) for lack of use, (b) if we believe that you have violated or acted inconsistently with the letter or spirit of this Agreement or the documents or 
agreements it incorporates by reference, (c) if we are unable to verify or authenticate any information you provide to us, or (d) if we believe that your actions may cause legal liability for you, our users or us. You agree that any termination of your account or access to all 
or any portion of the Site under any provision of this Agreement may be effected without prior notice, and acknowledge and agree that we may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such 
files or our Site. You also agree that we shall not be liable to you or any third party for any termination of your use of or access to all or any portion of the Site. Termination or suspension of your use of our Site in violation of Section 4.2 will not result in refunds 
of membership fees paid, if any, and you will forfeit the remaining period of your paid membership, if any.

<br><br>
<h1>15. Trademanrks; Copyrights; Proprietary Rights</h1>
<br>15.1 <b>Sportfast's Trademarks.</b> Sportfast trademarks and service marks, and other Sportfast logos, products and service names, are trademarks of Sportfast (the "Sportfast Trademarks"). Except as otherwise permitted by law, you agree not to display or use in any manner the Sportfast 
Trademarks without Sportfast's prior written consent.

<br><br>15.2 <b>Copyrights and Trademarks of Others.</b> Sportfast respects the intellectual property of others, and we ask our users to do the same. To the extent Sportfast uses a trademark that is the property of a third party, Sportfast shall provide clear notice to anyone viewing Sportfast's use of 
that trademark that (a) Sportfast does not own the trademark and that the trademark is the property of a third party, (b) Sportfast has no affiliation, connection or association with that third party, and (c) if applicable, that third party has not approved or sponsored Sportfast's use of the trademark 
in any way. We may, in appropriate circumstances and in our discretion, remove, or disable access to, material that infringes on the rights of others, and terminate access to our Site to those who may be repeat infringers. If you believe that your work has been copied in a way that constitutes 
copyright infringement, or your intellectual property rights have been otherwise violated, please provide our Copyright Agent the following information: 1.an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest; 
2.a description of the copyrighted work or other intellectual property that you claim has been infringed; 3.a description of where the material that you claim is infringing is located on the site; 4.your address, telephone number, and email address; 5.a statement by you that you have a good faith belief 
that the disputed use is not authorized by the copyright owner, its agent, or the law; 6.a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual 
property owner's behalf.
<br><br>Our Agent for Notice of claims of copyright or other intellectual property infringement can be reached as follows:
<br><br>By mail:
<br>Copyright Agent 
<br>6 Ninestone Ct
<br>San Rafael, CA 94903 
<br>By email: legal@sportfast.com

<br><br>15.3 <b>Proprietary Rights.</b> You acknowledge and agree that our Site contains proprietary and confidential information that is protected by applicable intellectual property and other laws. You also acknowledge and agree that content contained in sponsor advertisements or information presented to you 
through our Site or advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as consented to by Sportfast or advertisers in writing, you agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on our Site, in whole or in part.

<br><br>
<h1>16. No Resale</h1>
You agree not to reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any portion of Sportfast's Site, use of the Site, or access to the Site for any sales of goods or services, or promotion of a company, good, or service unrelated to the topic or spirit or the Game or Team.

<br><br>
<h1>17. Additional Terms</h1>
<br>17.1 <b>No Agency.</b> No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship between you and Sportfast is intended or created by this Agreement.

<br><br>17.2 <b>Governing Law.</b> Except as expressly provided in this Section, (a) this Agreement and the relationship between you and Sportfast shall be governed by the laws of the State of California without regard to its conflict of laws provisions, as such laws are applied to agreements entered into and to be performed entirely 
within California between California residents, and (b) you and Sportfast agree to submit to the personal and exclusive jurisdiction of the courts located within the State of California.

<br><br>17.3 <b>Assignment.</b> You agree that this Agreement, all rights herein, and all incorporated agreements may be automatically assigned by Sportfast, in our sole discretion, to one or more third parties in the event of a merger, acquisition, corporate reorganization, sale of all or substantially all of Sportfast's assets, or similar transaction.

<br><br>17.4 <b>No Guarantee.</b> We do not guarantee continuous, uninterrupted or secure access to our Site, and operation of our website may be interfered with by numerous factors outside of our control.

<br><br>17.5 <b>No Waiver.</b> Sportfast's failure to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision and does not waive our right to act 
with respect to subsequent or similar breaches.

<br><br>17.6 <b>Severance.</b> If any provision of this Agreement is found to be invalid by a court of competent jurisdiction, you and Sportfast nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and that the other provisions of this Agreement will remain in full force and effect.

<br><br>17.7 <b>Survival.</b> Sections 4.1, 4.2, 5.3 (License), 6.4 (Interference with Site), 7.2 (Release), 11 (Indemnity), 12 (Warranties; Liabilities), and 17.2 (Governing Law) shall survive any termination or expiration of this Agreement.

<br><br>17.8 <b>Limitation.</b> You and Sportfast each agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to the use of our Site or this Agreement must be filed within one (1) year after the 
claim or cause of action arose or be forever barred.

<br><br>17.9 <b>Titles.</b> The section titles in this Agreement are for convenience only and have no legal or contractual effect.

<br><br>By indicating during registration that you have read and agreed to this Agreement, you are agreeing that you have read and understand this Agreement and agree to all of the terms of this Agreement.