<?php
/** 
 * controller => contact
 * action => index
 */
$this->headTitle('Contact Us');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/contact.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/contact.js');
?>

<div id='contact-container'>
	<p class='clear darkest jumbo-text heavy'>Contact Us</p>
    <div class='clear white-back rounded-corners larger-text' id='contact-inner-container'>

		<form action="<?php echo $this->form->getAction(); ?>"
              enctype="<?php echo $this->form->getEnctype(); ?>"
              method="<?php echo $this->form->getMethod(); ?>"
              >
    	<?php echo $this->form->email;?>
        <p class='clear medium smaller-text' id='contact-email-subtext'>
        	Replies will be sent to this email
        </p>
        <?php echo $this->form->question;?>
        <?php echo $this->form->browser;?>
        <?php echo $this->form->submit;?>
        </form>
        <p class='clear smaller-text larger-margin-top medium'>
    	Or send your own email to support@sportfast.com
    </p>
    </div>
    
 </div>