<?php
/** 
 * controller => teams
 * action => index
 */
$this->headTitle($this->team->teamName);
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/team.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/profile.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/team.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/profile.js');
if ($this->captain) {
	// Used for reserve search function
	$this->headScript()->prependFile($this->baseUrl() . '/js/createsuccess.js');
}

?>

<?php
if ($this->fail) {
	// No team found, show failure
	echo "<p class='larger-margin-top left jumbo-text heavy width-100 center darkest'>Team not found.</p>";
	echo "<p class='clear largest-text heavy darkest width-100 center'>This team has been deleted.</p>";
	echo "<a href='/' class=' larger-margin-top clear larger-text medium width-100 center'>Back to home</a>";
	return;
}



	echo $this->placeholder('absolute')->captureStart();
	echo $this->partial('partials/global/alertBack.phtml');
	
	if ($this->team->remove && $this->team->remove != '0000-00-00') {
		// Team has been marked for removal
		echo $this->alert()->start('canceled');
			echo "<p class='largest-text darkest width-100 center heavy'>This team has been deleted.</p>";
			
			echo "<p class='medium width-100 center'>It will be removed within a few days.</p>";

			echo "<a href='/' class='clear larger-text larger-margin-top heavy green-button white' id='team-canceled-back'>Back to home</a>";
		echo $this->alert()->end();
	}
	
	if ($this->signupInvite) {
		
		echo $this->alert()->minimalSignup($this->user, $this->team->cityID, $this->cityLocation->location);
		
	}

	
	if ($this->captain) {
		// User is captain, show alerts for captain's management
			echo $this->alert()->start('manage-schedule','Click on a day to add/edit schedule.');
			
			echo "<div class='team-manage-calendar left'>";
			echo $this->calendar()->createCalendar($this->events, true, false, false, false, true, true);
			echo "</div>";
			
			echo "<p class='pointer medium action' id='team-manage-calendar-clear' tooltip='Clear entire schedule (future and past)'>clear schedule</p>";
			
			$winOrLossContent  = "<p class='left darkest larger-text'>vs. <span id='tooltip-team-manage-winOrLoss-opponent' class='darkest'>Unknown</span></p>";
			$winOrLossContent .= "<p class='right header medium x'>X</p>";
			$winOrLossContent .= "<div class='clear width-100 larger-margin-top larger-text'>";
			$winOrLossContent .= 	"<p class='button tooltip-team-manage-winOrLoss-button win-button'>Win</p>";
			$winOrLossContent .= 	"<p class='button tooltip-team-manage-winOrLoss-button loss-button'>Loss</p>";
			$winOrLossContent .= "</div>";
			$winOrLossContent .= "<p class='clear light pointer tie margin-top'>Tie</p>";
			$winOrLossContent .= "<p class='right light pointer remove-game margin-top'>Remove</p>";
			echo $this->tooltip('-team-manage-winOrLoss', $winOrLossContent);
			
			
			$futureEventContent  = "<p class='left heavy darkest larger-text' id='team-manage-schedule-date'></p><p class='right header medium x'>X</p>";
			$futureEventContent .= $this->generalForm->text->setName('teamManageScheduleOpponent')->setLabel('Opponent');
			$futureEventContent .= "<select class='clear' id='teamManageScheduleHour'>";//$this->manageScheduleTimeHour
			for ($i = 1 ; $i <= 12; $i++) {
				$selected = '';
				if ($i == 7) {
					$selected = 'selected';
				}
				$futureEventContent .= "<option " . $selected . ">" . $i . "</option>";
			}
			$futureEventContent .= "</select>";
			$futureEventContent .= "<p class='left team-manage-schedule-time-separator'>:</p>";
			/*$futureEventContent .= $this->manageScheduleTimeMinute;
			$futureEventContent .= $this->manageScheduleTimeAmPm;*/
			$futureEventContent .= "<select class='left' id='teamManageScheduleMinute'>
										<option>00</option>
										<option>15</option>
										<option>30</option>
										<option>45</option>
									</select>";
			$futureEventContent .= "<select class='left' id='teamManageScheduleAmPm'>
										<option selected>pm</option>
										<option>am</option>
									</select>";
			$futureEventContent .= $this->generalForm->text->setName('teamManageScheduleLocation')->setLabel('Location Name');
			$futureEventContent .= $this->generalForm->text->setName('teamManageScheduleAddress')->setLabel('Address');
			$futureEventContent .= "<div id='team-manage-schedule-location-results' class='clear'></div>";
			$futureEventContent .= "<p class='green-button clear-right right save-button'>Save</p>";
			$futureEventContent .= "<p class='button left delete-button remove-game'>Delete</p>";

			echo $this->tooltip('-team-manage-addGame', $futureEventContent);
			
			echo $this->alert()->end();
			
			// Remove player alert
			echo $this->removeplayeralert($this->team->players->getAll(), $this->team->teamName);
			
						
			// Edit team info alert
			echo $this->alert()->start('manage-team-info',"Click on anything to edit.");
				echo "<div class='team-manage-team-info-container width-100 left'>";
				echo 	"<div class='team-manage-team-info-tab-container width-100 clear larger-text'>";
				echo		"<p class='team-manage-team-info-tab left pointer team-manage-team-info-tab-selected'>Team Info</p>";
				echo		"<p class='team-manage-team-info-tab left pointer'>Advanced</p>";
				echo	"</div>";
				echo	"<div class='team-manage-team-info-lower-container width-100 clear'>";
				echo		"<div class='left' id='team-manage-team-info-img-outer-container'>
								<img src='" . $this->team->getProfilePic('medium') . "' class='left pointer' id='team-manage-team-info-img' />
								<div class='hidden clear margin-top' id='team-manage-team-info-img-container'>";
				foreach ($this->avatarNames as $fileName) {
					$class = 'left create-team-avatar pointer ';
					if ($fileName == $this->defaultAvatar) {
						$class .= ' create-team-avatar-selected';
					}
					echo "<img src='/images/teams/avatars/small/" . $fileName . "' class='" . $class . "' avatar='" . str_replace('.jpg','', $fileName) . "'/>";
					
					// preload large images
					echo "<img src='/images/teams/avatars/medium/" . $fileName . "' class='hidden'/>";
				}
				echo 			"</div>
							</div>";
				echo 		"<div class='team-manage-team-info-name-container left'>";
				echo 			"<p class='left smaller-text darkest'>Team Name</p>";
				echo 			"<input type='text' class='clear darkest heavy team-manage-team-info-name' id='team-manage-team-info-name' value='" . $this->team->teamName . "'/>";
				echo 		"</div>";
				echo 		"<div class='team-manage-team-info-name-container left larger-margin-top'>";
				
				echo 			"<p class='left smaller-text darkest'>Team Captain</p>";
					
					/*// User is head honcho
					foreach ($this->team->captains as $captain => $true) {
						$player = $this->team->players->getUser($captain);
						echo "<p class='clear largest-text darkest heavy team-manage-team-info-name pointer team-manage-team-info-captain-real' userID='" . $player->userID . "' id='team-manage-team-info-captain' defaultName='" . $this->team->players->getUser($captain)->getLimitedName('fullName',21) . "'>"
										 . $player->getLimitedName('fullName', 21) . "
									</p><span class='left header red hidden largest-text remove-captain pointer'>x</span>";
					}
					echo "<p class='green smaller-text clear pointer' id='team-manage-team-info-add-captain'>+ add captain</p>";
					echo			"<div class='clear hidden' id='team-manage-team-info-captain-container'>";
					
					foreach ($this->team->players->getAll() as $player) {
						if (!$this->team->isCaptain($player->userID)) {
							echo "<div class='left pointer team-manage-team-info-captain' playerName='" . $player->getLimitedName('fullName', 21) . "' userID='" . $player->userID . "'>";
							echo	$player->getBoxProfilePic('tiny', 'users', 'animate-opacity', 'dark-back');
							echo "</div>";
						}
					}
					echo				"<p class='margin-top medium smaller-text clear'>Note: you will not be able to access any management controls if you are no longer the captain.</p>";
					
					echo			"</div>";
					*/
			echo $this->changecaptain($this->team);
				
			echo 		"</div>";
			echo	"</div>";
			
			// Team Advanced Options
			echo	"<div class='team-manage-team-info-lower-container width-100 clear hidden'>";
			
			// Visibility
			echo 		"<div class='width-100 clear selectable-container' section='public'>
							<p class='selectable-text-section-title'>Visibility</p>";
							
			$what    = array('Public'  => array('selected' => $this->isPublic,
											    'tooltip'  => 'Your team will be visible to users looking for teams.'),
							 'Private' => array('selected' => $this->isPrivate,
							 					'tooltip'  => 'Your team will only be visible to your players.')
							);
			echo 			$this->signupsportform()->selectableText($what, true);
			echo	   '</div>';
			
			// Location
			echo 		"<div class='width-100 clear selectable-container' section='city'>
							<p class='selectable-text-section-title'>Location</p>";
							
			echo			"<input type='text' value='" . $this->team->city . "' id='team-manage-team-info-location' class='clear selectable-input' />";
			echo	   '</div>';

			
			// Roster Limit
			echo 		"<div class='width-100 clear selectable-container' section='rosterLimit'>
							<p class='selectable-text-section-title'>Maximum Players</p>";
							
			echo			"<input type='text' value='" . $this->team->rosterLimit . "' id='team-manage-team-info-roster-limit' class='clear selectable-input profile-manage-team-info-roster-limit'/>";
			echo	   '</div>';


			echo 	"</div>";
			echo "</div>";
			
			echo		"<div class='clear width-100 larger-margin-top hidden' id='team-manage-team-info-confirm-container'>";
			echo			"<p class='button team-manage-team-info-button larger-margin-top right' id='team-manage-team-info-save-changes'>Save changes</p>";
			echo			"<p class='team-manage-team-info-button right medium smaller-text alert-cancel-button pointer'>Cancel</p>";
			echo 		"</div>";
				
			echo $this->alert()->end();
			
			
			// Message
			echo $this->alert()->messageAlert();
			
			
			// Reserves
			echo $this->alert()->start('reserves', "Edit " . $this->team->teamName . "'" . (substr($this->team->teamName, -1) == 's' ? '' : 's') . " Reserves");
			
			echo "<div class='clear width-100' id='team-reserve-alert-container'>";
			
			if (!$this->team->reserves->hasValue('users')) {
				// no reserves, show description
				$player = new Application_Model_User();
				$player->firstName = 'John';
				$player->lastName = 'Charlie';
				$player->userID = 300;
				
				echo "<div class='left team-reserve-player hidden'>"
							 . $player->getBoxProfilePic('medium')
							 . "<div class='hover-dark profile-player-overlay-container'>"
								. "<div class='profile-player-overlay'>"
									. "<p class='white width-100 center left larger-margin-top team-reserve-name'>" . $player->shortName . "</p>"
									. "<div class='clear larger-margin-top width-100'>
											<div class='red-button auto-center clear team-reserve-remove' userID='" . $player->userID . "'>remove</div>
										</div>
								   </div>
							   </div>
						  </div>";
				
				echo "<p class='margin-top width-100 darkest' id='team-reserve-none'>
						Players on your reserves list can be invited to play in any upcoming team game.  
						They do not receive any team notifications or updates, and will only be able to join a game if a team captain invites them.
					  </p>";
			} else {
				foreach ($this->team->reserves->getAll() as $player) {
					echo "<div class='left team-reserve-player'>"
							 . $player->getBoxProfilePic('medium')
							 . "<div class='hover-dark profile-player-overlay-container'>"
								. "<div class='profile-player-overlay'>"
									. "<p class='white width-100 center left larger-margin-top team-reserve-name'>" . $player->shortName . "</p>"
									. "<div class='clear larger-margin-top width-100'>
											<div class='red-button auto-center clear team-reserve-remove' userID='" . $player->userID . "'>remove</div>
										</div>
								   </div>
							   </div>
						  </div>";
							 
				}
			}
			echo "</div>";
			
			
			echo "<div class='clear width-100' id='team-reserve-alert-userName-container'>" 
					. $this->reserveUserName
				. "</div>";
				
			echo "<div class='clear' id='create-userName-results-container'></div>";
			
			echo $this->alert()->end();
				
			
	}
	
	if ($this->addToTeam) {
		// User not added to game from email
		echo $this->alert()->start('addToGame',"");
		
		echo "<p class='clear darkest width-100 center largest-text heavy'>" . $this->addToTeam . "</p>";
				
		echo $this->alert()->end();
	}

	if ($this->team->isSystemCreated() && !$this->userOnTeam && $this->topAlert) {
		// Show alert box
		$content = "<p class='white heavy left width-100 center'>This is a Sportfast-created " . $this->team->sport . " team.</p>";
		echo $this->topAlert('sportfast-team', $content);
	}
	
	echo $this->alert()->confirmAlert();
	
	
	if ($this->invitesSent ||
		$this->messageSent) {
		// Invites sent from previous page, show alert
		echo $this->alert()->start('success');
		echo "<p class='largest-text darkest width-100 center heavy'>" . ($this->invitesSent ? 'Invites' : 'Message') . " sent.</p>";

		echo $this->alert()->end();
	}
	
	if ($this->captain) {
		$this->headScript()->prependFile($this->baseUrl() . '/js/createsuccess.js');
		//$this->headLink()->prependStylesheet($this->baseUrl() . '/css/create.css');
		
		echo $this->alert()->inviteAlert();
	}
	
	
	echo $this->placeholder('absolute')->captureEnd();
?>


<?php
// Narrow left column
$this->placeholder('narrowColumn')->captureStart();
echo "<img src='" . $this->team->getProfilePic('large') . "' class='rounded-corners'/>";

$ratings = array('skill', 'sportsmanship', 'attendance');

echo $this->narrowcolumnsection()->start(array('title' => 'Team Ratings'));

if ($this->team->players->hasValue('users')) {
	// Players exist, show average ratings
	echo "<div class='profile-narrow-rating-container clear'>";
	foreach ($ratings as $rating) {
		echo $this->partial('partials/global/ratingBar.phtml', array('rating' => $this->team->getAverage($rating),
																	 'ratingLabel' => $rating));
	}
	echo "</div>";
} else {
	// No players
	echo "<p class='width-100 left center light'>No players</p>";
}
echo $this->narrowcolumnsection()->end();

// Previous Games
echo $this->narrowcolumnsection()->start(array('title' => 'Previous Games'));
if (!$this->previousGames) {
	// No games
	echo "<p class='clear light'>No previous games were found.</p>";
} else {
	foreach ($this->previousGames as $game) {
		echo "<div class='team-narrow-game-container clear width-100'>";
		echo 	"<p class='dark left'>vs. " . $game->getLimitedName('opponent', 16) . "</p>";
		echo	"<p class='largest-text heavy green right profile-narrow-winOrLoss center'>" . $game->winOrLoss . "</p>";		
		echo	"<p class='light clear-left'>" . $game->getDay() . "</p>";

		echo "</div>";
	}
}
echo $this->narrowcolumnsection()->end();

// Leagues
/*
echo $this->narrowcolumnsection()->start(array('title' => 'Leagues'));
if (!$this->team->leagues->hasValue('leagues')) {
	// No leagues
	echo "<p class='clear light'>This team is not signed up for a league.</p>";
} else {
	foreach ($this->team->leagues->getAll() as $league) {
		echo "<div class='team-narrow-game-container clear width-100'>";
		echo 	"<p class='darkest left'>" . $league->getLimitedName('leagueName', 16) . "</p>";
		echo	"<p class='dark clear'>\"" . $league->leagueLevel . "\" Level&nbsp;</p>";
		echo	"<p class='left light'>" . $league->getStartFormat('M') . "-" . $league->getEndFormat('M') . "</p>";
		echo "</div>";
	}
}
echo $this->narrowcolumnsection()->end();
*/

$class = 'width-100 left narrow-column-calendar-container';
if ($this->captain) {
	// User is captain, make calendar clickable
	$class .= ' calendar-captain';
}

echo "<div class='" . $class . "'>";
echo $this->calendar()->createCalendar($this->events, true);
echo "</div>";


$this->placeholder('narrowColumn')->captureEnd();


// Store universal team details in hidden container
if ($this->team->hasValue('captains')) {
	$captains = array_keys($this->team->captains);
	$captains = implode(',',$captains);
} else {
	$captains = '';
}

echo "<span id='team-details' 
			teamID='" . $this->team->teamID . "' 
			idType='teamID' 
			actingUserID='" . $this->user->userID . "' 
			captains='" . $captains . "'
			city='" . $this->team->city . "'
			rosterLimit='" . $this->team->rosterLimit . "'
			sport='" . $this->team->sport . "'
			public='" . ($this->isPublic ? 'public' : 'private') . "'
			teamName='" . $this->team->teamName . "'
			nextGameID='" . ($this->nextGame ? $this->nextGame->teamGameID : '') . "'
			" . ($this->firstTeam ? "firstType = 'true'" : '') . ">
	 </span>";
?>

<?php
if ($this->userOnTeam) {
	$options = array();
	$basicOptions = array(array('text' => 'leave',
						  		'img'  => 'leave',
								'tooltip' => 'Leave this team')
						  );
	
								
	$recurringOptions = array(array('text' => 'reminders',
									'img'  => 'reminder',
									'tooltip' => 'Manage any reminders for this game')
							  );
									
	$captainOptions = array(array('text' => 'schedule',
								  'img'  => 'schedule',
								  'tooltip' => "Edit the schedule"),
							array('text' => 'reserves',
								  'img'  => 'reserves',
								  'tooltip' => "Edit the reserves list"),
							array('text' => 'edit team',
								  'img'  => 'edit',
								  'tooltip' => "Edit this team's details"),
							array('text' => 'message',
								  'img'  => 'message',
								  'tooltip' => "Send an email message to the players"),
							array('text' => 'delete',
								  'img'  => 'delete',
								  'tooltip' => 'Delete this team'),
							array('text' => 'invite',
								'img'  => 'invite',
								'tooltip' => 'Invite other players'));
	
	
	if ($this->captain) {
		// Is captain
		foreach ($captainOptions as $option) {
			$options[] = $option;
		}
	
	}
	
	
	foreach ($basicOptions as $option) {
		$options[] = $option;
	}
	
	
	
	echo $this->partial('partials/profile/options.phtml', array('options' => $options));
}
?>



<header class='clear profile-name-container'>
	<p class='profile-name heavy darkest clear'>
    	<?php echo $this->team->teamName;?>
	</p>
    <div class='profile-city-container clear'>
        <p class='light clear larger-text'>
            <span class='darkest'><?php echo $this->team->city . '</span> &nbsp;' . $this->team->sport . ' Team &nbsp;<span class="darkest">' . $this->team->record . '</span>';?>
        </p>    

    </div>
</header>


 <?php
		
	if ($this->userOnTeam) {
		// You are on team
		?>
        <!--
		<div id='profile-buttons-container-holder' class='right'></div>
			<div id='profile-buttons-container' holder='profile-buttons-container-holder' class='absolute'>
				<div class='profile-buttons-inner-container left'>
					<div class='profile-animate-buttons light-back pointer' tooltip='Show options'>
						<img src='/images/global/arrows/left/medium.png' class='left' />
					</div>
					<div class='profile-buttons-innermost-container right'>
		
		<p class='dark smaller-text right current-position'>You are currently <?php echo ($this->captain ? 'Team Captain' : 'a member');?>.</p>
		<p class='red-button clear-right leave-button margin-top right' id='leave-button' style='margin-right:0'>
			Leave
		</p>
    <?php
		if ($this->captain) {
			// User is captain
			echo "<div class='larger-margin-top clear-right profile-buttons-second-row' style='margin-right:0'>" . $this->inviteButton . "</div>";
			echo "<div class='larger-margin-top right profile-buttons-second-row'>" . $this->manageButton . "</div>";
		}
	?>
        	</div>
        </div>
    </div>
   -->
    <?php } else {
			$lower = '';
			$class = '';
			$text = 'Join';
			$id    = 'join-button';
			$tooltip = 'Join Team';
			
			if (!$this->team->isSystemCreated() && 
				$this->hasCaptain &&
				!$this->invited) {
				// Not sportfast created team, do not allow any user to join without request
				$text = 'Request to Join';
				$id   = 'request-join-button';
				$tooltip = 'Request to join team.';
			}
			/*if ($this->team->minSkill > $this->user->getSport($this->team->sport)->skill &&
				!$this->invited) {
				// User is not good enough for this team
				$class = 'transparent default';
				$id = '';
				$lower = '<p class="light clear-right smaller-text margin-top">You must have a minimum skill of ' . $this->team->minSkill . ' to join.';
			}*/
			?>
            <div id='profile-buttons-container'>
    		<p class='green-button right larger-text join-button heavy <?php echo $class;?>' id='<?php echo $id;?>' tooltip='<?php echo $tooltip;?>'>
            	<?php echo $text;?>
            </p>
            <?php echo $lower; ?>
            </div>
    <?php } ?>
		
		
        
    
<?php 
// Create header for next game section
$nextGameHeader = '';
if ($this->nextGame) {
	// Next game exists
	$nextGameHeader .= "<div class='right profile-section-bold-subheader'>";
	$nextGameHeader .= 		"<p class='right darkest heavy'><span class='inherit confirmed'>" . $this->countConfirmedPlayers . "</span> " . ($this->countConfirmedPlayers == 1 ? 'player' : 'players') . " " . ($this->nextGame->countMaybeConfirmedPlayers() > 0 ? "<span class='smaller-text medium'>+" . $this->nextGame->countMaybeConfirmedPlayers() . " maybe</span>" : '') . "</p>";
	$nextGameHeader .= "</div>";
}
echo $this->partial('partials/global/sectionHeaderBold.phtml',array('title'   => 'next game',
																	'content' => $nextGameHeader)); 
																	
?>

<div class='clear width-100' id='team-next-game-container'>
<?php
	if (!$this->nextGame) {
		// No next game
?>
	<p class='center width-100 light larger-text none-text'> There are no games in the near future.</p>
<?php } else { 
		// Next game and user on team, show info
?>
	<div class='team-next-game-left-container left'>
    	<p class='left largest-text darkest'>vs. <span class='heavy inherit'><?php echo $this->nextTeamName;?></span></p>
        <p class='clear darkest' tooltip='<?php echo $this->nextGame->gameDate->format('M j');?>'>
        	<?php echo $this->nextDay;?> at <?php echo $this->nextHour;?>
        </p>
        <p class='clear darkest'>
        	<?php echo $this->nextLocationName;?> <a href='http://www.maps.google.com/maps?f=d&q=<?php echo $this->nextLocationStreetAddress;?>' target='_blank' class='light'>directions</a>
        </p>
    </div>
	
    <?php
		if ($this->userNextGame) {
			// User is attending next game
			$inClass  = '';
			$outClass = '';
			$existingID = ' existingID="update"';
			if ($this->userNextGame == 'confirmed') {
				$inClass = 'inner-shadow member-schedule-button-selected';
			} else {
				$outClass = 'inner-shadow member-schedule-button-selected';
			}
			
		} else {
			// User either has not responded, or is definitely not going
			$outClass  = '';
			$inClass = '';
			$existingID = '';
		}
		if ($this->userOnTeam || $this->invitedToNextGame) {
			// User is on team or is reserve invited to play
	?>
    <!--
    <div class='team-next-game-right-container right' <?php echo $this->nextGameType . $this->nextGameTypeID . $this->nextGameTeamID . $existingID;?>>
        <p class='darkest center'>Are you in, or are you out?</p>
        <p class='button larger-text schedule-in <?php echo $inClass;?>'>in</p>
        <p class='button larger-text schedule-out <?php echo $outClass;?>'>out</p>
	</div>
    -->
    
    <?php
	echo $this->partial('partials/global/confirmed.phtml', array('game' => $this->nextGame,
																 'userID' => $this->user->userID));
	?>


<?php 
		}
}
echo "</div>";

// Create header for players section
$playersHeader  = "<div class='right profile-section-bold-subheader'>";
$playersHeader .= 		"<p class='right medium'>" . $this->totalPlayers . " out of " . $this->rosterLimit . "</p>";
$playersHeader .= "</div>";
if ($this->nextGame) {
	$playersHeader .= "<div class='left profile-section-bold-subheader team-player-going-description-container'>";
	//$playersHeader .= 		"<img class='left' src='/images/team/confirm/small.png' />";
	$playersHeader .=		"<div class='left green-back profile-confirm'></div>";
	$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Going to next game</p>";
	//$playersHeader .= 		"<img class='left' src='/images/team/deny/small.png' />";
	$playersHeader .=		"<div class='left dark-red-back profile-confirm'></div>";
	$playersHeader .= 		"<p class='left smaller-text medium team-players-section-header-going'>Not going to next game</p>";
	$playersHeader .= "</div>";
}
echo $this->partial('partials/global/sectionHeaderBold.phtml',array('title'   => 'players',
																	'content' => $playersHeader)); 

echo "<div id='team-players-container' class='clear width-100'>";

if ($this->team->players->hasValue('users')) {
	// Players exist
	echo $this->playerssection($this->team->players->users, $this->nextGame);
} else {
	echo "<p class='none-text larger-text light width-100 center'>There are no players.</p>";
}
echo "</div>";

// Reserves section
if ($this->userOnTeam) {
	if (!$this->captain && !$this->team->reserves->hasValue('users')) {
		// Is not captain and there are no reserves, do not display
	} else {
		// Is captain with no reserves OR there are reserves
		echo "<div class='clear width-100'>
				<div class='clear pointer' id='team-show-reserves'>
					<img src='/images/global/body/down_arrow.png' class='left margin-top' /><p class=' indent medium left'>show reserves</p>
				</div>
				<div class='clear pointer hidden' id='team-hide-reserves'>
					<img src='/images/global/body/up_arrow.png' class='left margin-top' /><p class=' indent medium left'>hide reserves</p>
				</div>";
		if (!$this->team->reserves->hasValue('users')) {
			// Is captain and no reserves, show explanation
			echo "<p class='left indent darkest pointer' tooltip='Your reserves list allows you to quickly invite backup players to your next game.'>?</p>";
		}
			
		echo "<div class='clear hidden margin-top' id='team-reserves-container'>";
		
		
		foreach ($this->team->reserves->getAll() as $player) {
			$confirmed = '';
			if ($this->nextGame) {
				if ($this->nextGame->userConfirmed($player->userID)) {
					$confirmed = "<div class='team-reserve-confirmed'></div>";
				} elseif ($this->nextGame->userNotConfirmed($player->userID)) {
					$confirmed = "<div class='team-reserve-not-confirmed'></div>";
				}
			}
			echo "<div class='left team-reserve-player' tooltip='" . $player->shortName . "' userID='" . $player->userID . "'>" 
					. $player->getBoxProfilePic('small', 'users', 'animate-opacity', 'dark-back')
					. $confirmed
					. "</div>";
		}
		
		if ($this->captain) {
			// Is captain, show "add user to reserve" box
			echo "<div class='left box-img-container-small pointer white-background animate-darker' style='margin-left: 1px;' tooltip='Add player to your reserves list.' id='team-reserve-add'>
					<p class='heavy medium width-100 center margin-top'>+ add</p>
				  </div>";
		} 
		
		echo "<div class='clear width-100'>
				<p class='green-button auto-center margin-top hidden' id='team-reserve-invite' tooltip='Invite selected reserve players to play in the next game.'>invite</p>
			  </div>";

			
		echo "</div>";
		echo "</div>";
	}
}
		

echo $this->partial('partials/global/sectionHeaderPlain.phtml',array('title' => 'Recent Activity'));

if ($this->userOnTeam) {
	// User is on team, allow to post
?>
<div id='team-post-container' class='clear width-100'>
	<?php echo $this->user->getBoxProfilePic('small');?>
    <?php echo $this->postForm;?>
</div>

<?php
	}
echo $this->profilenewsfeed()->create($this->newsfeed);
?>

