<?php
/* 
* controller => how
* action => index
*/
$this->headTitle('How Does It Work');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/how.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/how.js');
?>
<p class='how-title heavy'>
	Play <span class='green heavy'>recreational sports</span> with other athletes.
</p>
<!--
<p class='how-title heavy' id='how-title2'>
	Sweet.  So do we.
</p>-->
<div id='how-icon-holder'></div>
<?php
$this->placeholder('absolute')->captureStart();
?>
<div id='how-icon-container' class='absolute' holder='how-icon-holder'>
	<div id='how-icon-inner-container' class='dark-back dropshadow'>
    <p class='clear white heavy width-100 center larger-margin-top'>How it works</p>
	<?php 
	$partial = array(
			array('ele' => array('image'   => 'clock',
								 'header'  => 'Input preferences',
								 'subtext' => "To find you the perfect game, we need to know what you want.  Give us your preferences and we'll get you a game.")
								 ),
			array('ele' => array('image'   => 'cogs',
								 'header'  => 'Sportfast works',
								 'subtext' => 'Our system analyzes local athletes\' skill, age, and availability to create optimal games open to everyone.')
								 ),
			array('ele' => array('image'   => 'cursor',
								 'header'  => 'Pick a game',
								 'subtext' => 'Join the games you want to play. Easily manage your upcoming events with our schedule.')
								 ),
			array('ele' => array('image'   => 'sport',
								 'header'  => 'Show up and enjoy',
								 'subtext' => 'When enough players join, the game is on!  All you need to do is show up and play.')
								 )
	);
	
	echo $this->howicon('partials/how/icon.phtml',$partial); 
	?>
    </div>
</div>
<?php
$this->placeholder('absolute')->captureEnd();
?>
<!-- bug where first child how-section will not clear how-icon-holder -->
<div class='clear'></div>
<div class='left'>
<?php
$partial = array(
		array('ele' => array('header'  => 'Play on your own level.',
							 'subtext' => "We believe that everyone should have the opportunity to compete on their own level.  Games, teams, and 
							 				tournaments are formed with this principal in mind.  Players are matched based on age, skill, and position 
											to provide the most competitive (and fair) games possible.")
							 ),
		array('ele' => array('header'  => 'Rate and be rated.',
							 'subtext' => "Ever wonder how other players view your playing style?  Now, you can finally know.  After playing in a game, 
							 				other players will rate you based on 3 categories: skill, sportsmanship, and the best part 
											 of your game.  With our rating system, you can easily track your progress over time.")
							 ),
		array('ele' => array('header'  => 'Crave competition?  Find a team.',
							 'subtext' => "Putting together a league team is always a hassle, and finding one to join is near impossible, but we take the hassle 
											 out by automatically matching players of comparable skill and complementary position.  We'll even organize and register your newly-formed 
											 team with a local league, so all you need to worry about is showing up and playing hard.")
							 ),
		/*array('ele' => array('header'  => 'Mix it up.',
							 'subtext' => "Like most gifted athletes, you play more than one sport.  Why should you be bogged down to the same game with the same people week after week?  
							 				With Sportfast, you can spice up your week with football Saturday, basketball Tuesday, and soccer Friday--all within a few miles of your house.")
							 )*/
		array('ele' => array('header'  => 'Organize.',
							 'subtext' => "Tired of organizing your weekly pickup game or league team week after week?  Our automated system makes it easy to coordinate
							 				who is going, how many people are needed, and where it's going to be.  Why should you have to spend your valuable time contacting people
											when our system can do it for you?")
							 )
);

echo $this->partialLoop('partials/how/lowerSection.phtml',$partial); 

?>
</div>

<p class='clear jumbo-text heavy margin-top'>
What sports?
</p>
<p class='clear darkest larger-text'>
We currently support the following sports:
</p>

<div class='clear larger-margin-top width-100%'>
    <div id='how-sport-icons-container'>
        <div id='how-sport-icons-inner-container'>
<?php
foreach ($this->sports->getAll() as $sport) {
	echo "<img src='" . $sport->getIcon('large','outline') . "' class='left medium-back how-sport-icon' sport='" . $sport->sport . "'/>";
}
?>
        </div>
    </div>
</div>

<div class='clear margin-top dark largest-text width-100 center heavy' id='how-sport'>
</div>

<a href='/signup' class='jumbo-text green-button heavy clear' id='how-signup-button'>
SIGNUP FREE
</a>
