<?php
/** 
 * controller => mail
 * action => add-user-subscribe-game
 */
$this->headTitle('Add to Game');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/mail.css');
?>

<div id='mail-add-user-success-container' class='white-back alert-container dropshadow'>
<?php
if (!$this->fail) {
	// added to game
	$upper = 'You have been added to the roster.';
} elseif ($this->fail == 'already') {
	$upper = 'You are already in this game.';
} elseif ($this->fail == 'full') {
	$upper = 'This game is full.';
}
?>

<p class='width-100 center clear largest-text darkest heavy'><?php echo $upper;?></p>
<div class='clear width-100'>
    <a href='/games/<?php echo $this->gameID;?>' class='clear larger-margin-top button auto-center larger-text heavy' style='width:8em'>view game</a>
</div>

</div>