<?php
/** 
 * controller => mail
 * action => add-user-subscribe-game
 */
$this->headTitle('Add to Game');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/mail.css');
?>

<div id='mail-add-user-success-container' class='white-back alert-container dropshadow'>
<?php
$upper = $lower = $lowerClass = '';
if (!$this->fail) {
	// added to game
	$upper = 'You will be counted as:';
	
	if ($this->confirmed == '1') {
		$lower = 'IN';
		$lowerClass = 'green';
	} elseif ($this->confirmed == '2') {
		$lower = 'MAYBE';
		$lowerClass = 'medium';
	} elseif ($this->confirmed == '0') {
		$lower = 'OUT';
		$lowerClass = 'red';
	}
} elseif ($this->fail == 'already') {
	$lower = 'You are already in this game.';
} elseif ($this->fail == 'full') {
	$lower = 'This game is full.';
}
?>

<p class='width-100 center clear medium'><?php echo $upper;?></p>
<p class='clear width-100 center darkest largest-text heavy margin-top <?php echo $lowerClass;?>'><?php echo $lower;?></p> 
<div class='clear width-100'>
    <a href='/games/<?php echo $this->gameID;?>' class='clear larger-margin-top button auto-center larger-text heavy' style='width:8em'>view game</a>
</div>
<p class='clear smaller-text larger-margin-top medium'>Please <a href='/games/<?php echo $this->gameID;?>' class='darkest underline'>login</a> for more details.</p>

</div>