<?php
$this->headTitle('Mail Sent');
?>
<div class='white-back' style='width: 54em; position:absolute; top:50%; margin-top: -8em;left:50%; margin-left: -27em;'>
    <p class='width-100 center largest-text darkest clear margin-top heavy'>
    Your question, comment, or lovely haiku has been sent.
    </p>
    
    <p class='clear width-100 center larger-text medium'>
    Our support team will get back to you shortly.
    </p>
    
    <a class='clear larger-text button larger-margin-top' href='/' style='margin-left: 17em;'>
    Back to homepage
    </a>
</div>