<?php
/** 
 * controller => mail
 * action => unsubscribe-game
 */
$this->headTitle('Unsubscribed');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/mail.css');
?>

<div id='mail-add-user-success-container' class='white-back alert-container dropshadow'>

<p class='largest-text darkest heavy clear width-100 center'>
	You have been unsubscribed.
</p>

<p class='medium clear width-100 center larger-margin-top'>
	If any issues arise, please contact us at support@sportfast.com
</p>

</div>