<?php
//$this->partialLoop()->view->myVariable
?>
<div class='how-icon-section'>
	<img src='/images/how/icons/<?php echo $this->ele['image'];?>.png' class='how-icon-img' />
    <p class='how-icon-num white bold'>
        <?php echo $this->partialCounter;?>
    </p>
    <p class='how-icon-header white bold'>
    	 <?php echo $this->ele['header'];?>
	</p>
    <p class='how-icon-subtext medium'>
    	<?php echo $this->ele['subtext'];?>
	</p>
</div>