<?php
$sport = $this->sport;
echo "<div class='signup-sport-icon-container'><p class='white pointer header signup-sports-remove' tooltip='Remove " . $sport . "'>X</p>";
echo "<img src='/images/signup/sports/icons/" . $sport . ".png' class='sport-icon-large signup-sport-icon pointer' id='signup-sport-icon-" . $sport . "' tooltip='" . ucwords($sport) . "' alt='" . ucwords($sport) . "'/>";
echo "</div>";