<div class='signup-section-container' id='signup-section-container<?php echo $this->currentStep;?>'>
    <div class='signup-section-title-container'>
            <p class='signup-section-title header white'><?php echo strtoupper($this->title);?></p>
            <img src='/images/global/section_header_finish.png' class='section-header-finish' />
            <p class='signup-section-steps header darkest'><span class='signup-step'>step </span><?php echo '<span class="signup-step-bold header">' . $this->currentStep . '</span>
					<span class="signup-step"> of ' . $this->totalSteps . '</span>';?></p>
    </div>